dtinit/data-transfer-project

portability-core/src/test/java/org/dataportabilityproject/job/CrypterImplTest.java

Add a test for CrypterImplTest

---

bin/build_and_run_jar.sh
config/gcp/build_and_upload_docker_image.sh

Use a different debug port for different binaries so they don't conflict

---

client/src/app/app.component.spec.ts
client/src/app/simplelogin/simplelogin.component.spec.ts

There are several more things that still need to be fixed

A couple fixes to get 'ng test' working for #22

---

config/gcp/setup_gke_environment.sh

This does not appear to be scriptable unfortunately
Fixes #49

Add Stackdriver instructions to the GKE setup script

---

portability-api/src/main/java/org/dataportabilityproject/webapp/ConfigureHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/Oauth2CallbackHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/OauthCallbackHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/SetupHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/SimpleLoginSubmitHandler.java
portability-core/src/main/java/org/dataportabilityproject/ServiceProviderRegistry.java
portability-core/src/main/java/org/dataportabilityproject/shared/ServiceMode.java
portability-core/src/main/java/org/dataportabilityproject/shared/ServiceProvider.java

Add overloaded function for getOnlineAuthData that specifies ServiceMode

---

config/environments/prod/index.html

I updated the static content on our gcp bucket to reflect changes made to angular app (for testing #8)

Update index.html in prod to reflect updated content.

---

portability-core/src/main/java/org/dataportabilityproject/serviceProviders/microsoft/MicrosoftServiceProvider.java

prompt when exporting cal data from microsoft: 
prompt when importing cal data to microsoft: 
I deleted all the extra scopes as well since those aren't supported in the oauth flow (yet).

Limit scopes for AuthDataGenerators for MicrosoftServiceProvider when importing/exporting calendar data.

---

portability-core/src/main/java/org/dataportabilityproject/shared/ServiceProvider.java

Delete deprecated versions of get*AuthDataGenerator that don't use serviceMode.

---

portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerImpl.java

Forgot to push this per your comment on the previous commit.

Remove debug condition. Forgot to add to previous commit

---

extensions/cloud/portability-cloud-google/pom.xml
extensions/cloud/portability-cloud-microsoft/pom.xml
extensions/data-transfer/portability-data-transfer-google/pom.xml
extensions/data-transfer/portability-data-transfer-microsoft/pom.xml
pom.xml
portability-cloud/pom.xml
portability-gateway/pom.xml
portability-spi-cloud/pom.xml
portability-spi-gateway/pom.xml
portability-spi-transfer/pom.xml
portability-test-utilities/pom.xml
portability-transfer/pom.xml
portability-types-client/pom.xml
portability-types-transfer/pom.xml

This pull request incorporates the new Gradle-based module structure into the existing Maven build.
If the Maven modules need to change, don't worry about the Gradle configuration - I'll mirror the changes after they have been made.

Maven modules

---

client/e2e/app.e2e-spec.ts
client/e2e/app.po.ts

Set correct protractor test expectation so e2e tests pass

---

.travis.yml
client/protractor-ci.conf.js

Make Travis run Angular end-to-end tests

---

config/gcp/build_and_upload_docker_image.sh

Label docker images with git commit

---

client/src/app/backend.service.ts
client/src/app/next/next.component.html
client/src/app/next/next.component.ts
client/src/app/start-copy/start-copy.component.html
client/src/app/start-copy/start-copy.component.ts
portability-api/src/main/java/org/dataportabilityproject/webapp/SetupHandler.java

For using the new data types module (#71)
This requires a new binary and static content build (#67)

Use new DataTypes from portability-client-types in SetupHandler. 

---

config/environments/qa/index.html
config/environments/qa/settings/common.yaml

This pushes frontend and binary changes from #80 and #89 to qa  
#67

update qa index.html to reflect new content from #80 and #89, explicitly turn off encryptedFlow in qa

---

config/environments/prod/index.html
config/environments/prod/settings/common.yaml

This updates the prod binary and static content with changes from #80 and #89 
Front end changes tracked in: #67

Update index.html for prod and explicity turn off encryptedFlow

---

config/environments/prod/index.html
config/environments/qa/index.html

This updates the binary and static content with changes from #97 in prod and in qa 
Front end changes tracked in: #67

Update index.html for prod and qa to reflect deployed content

---

portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/JobAuthorization.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/PortabilityJob.java

Putting this in a separate object in case we want to persist this independently of the job.  Added basic state transition validation.

Add JobAuthorization data to the new PortabilityJob with associated state validation

---

portability-core/src/main/java/org/dataportabilityproject/serviceProviders/google/contacts/GoogleContactsService.java
portability-core/src/test/java/org/dataportabilityproject/serviceProviders/google/contacts/GoogleContactsServiceTest.java

Cleaning up code and adding batch request to Google Contacts API.  
How comfortable are we with this amount of streaming and generic types?

cleaning up code

---

config/environments/qa/index.html

This fixes the frontend issues in QA, and is already deployed to our API server (#67)
Been a while since we have deployed, but according to the last PR tagged in #67, we think this deploys changes from #107

Update index.html in QA to reflect the latest changes

---

extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudDatastore.java
extensions/cloud/portability-cloud-local/src/main/java/org/dataportabilityproject/cloud/local/InMemoryKeyValueStore.java
extensions/cloud/portability-cloud-microsoft/src/main/java/org/dataportabilityproject/cloud/microsoft/cosmos/CosmosStore.java
extensions/cloud/portability-cloud-microsoft/src/test/java/org/dataportabilityproject/cloud/microsoft/cosmos/CosmosStoreTest.java
portability-api/src/main/java/org/dataportabilityproject/webapp/CryptoHelper.java
portability-api/src/main/java/org/dataportabilityproject/webapp/DataTransferHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/Oauth2CallbackHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/OauthCallbackHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/SetupHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/SimpleLoginSubmitHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/StartCopyHandler.java
portability-core/src/main/java/org/dataportabilityproject/job/JobUtils.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/storage/JobStore.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/JobAuthorization.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/LegacyPortabilityJob.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/LegacyPortabilityJobConverter.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/PortabilityJob.java
portability-worker/src/main/java/org/dataportabilityproject/worker/JobPollingService.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerImpl.java
portability-worker/src/test/java/org/dataportabilityproject/worker/JobPollingServiceTest.java

Migrate JobState to the new modular structure

---

portability-types-transfer/src/main/java/org/dataportabilityproject/types/transfer/models/calendar/Property.java
portability-types-transfer/src/main/java/org/dataportabilityproject/types/transfer/models/calendar/RecurringEvent.java

Building a class for recurring events in calendar.

Recurring events

---

portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/JobAuthorization.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/PortabilityJob.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/InMemoryTransferCopier.java
portability-worker/build.gradle
portability-worker/src/main/java/org/dataportabilityproject/worker/JobPollingService.java
portability-worker/src/main/java/org/dataportabilityproject/worker/PortabilityInMemoryTransferCopier.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerImpl.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerJobMetadata.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerModule.java
portability-worker/src/test/java/org/dataportabilityproject/worker/JobPollingServiceTest.java

Also removed storage of private key

Build worker without dependency on legacy portability core objects

---

.travis.yml

This fixes travis Node failure:
E/launcher - session not created exception: Chrome version must be >= 63.0.3239.0

Update travis.yml to use correct chrome version

---

portability-spi-cloud/build.gradle
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/extension/CloudExtension.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/package-info.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/storage/BucketStore.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/storage/CryptoKeyStore.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/storage/JobStore.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/JobAuthorization.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/LegacyPortabilityJob.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/PortabilityJob.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/TypeManager.java
portability-spi-cloud/src/test/java/org/dataportabilityproject/spi/cloud/types/PortabilityJobTest.java

reformat portability-spi-cloud directory

---

libraries/security/src/main/java/org/dataportabilityproject/security/RsaSymmetricKeyGenerator.java
portability-gateway/build.gradle
portability-gateway/src/main/java/org/dataportabilityproject/gateway/action/startjob/StartJobAction.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/action/startjob/StartJobActionModule.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/action/startjob/StartJobActionRequest.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/action/startjob/StartJobActionResponse.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/CopySetupHandler.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/ImportSetupHandler.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/JWTTokenManager.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/ReferenceApiUtils.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/SetupHandler.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/SimpleLoginSubmitHandler.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/StartCopyHandler.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/TokenManager.java

Migrate remaining handlers to the gateway including the TokenManager

Migrate remaining handlers to the gateway

---

extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudExtension.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/extension/CloudExtension.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/extension/CloudExtensionModule.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerMain.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerModule.java

Tested running worker locally
for #172

Give cloud extension implementations the choice whether to use Guice or not

---

portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/extension/CloudExtensionModule.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerExtensionContext.java

My copyright generator in Intellij was mesesd up, fixed it now

Remove accidental extra copyright text

---

Documentation/Integration.md

This starts to capture the areas that have to be documented for integration providers.

Create the initial outline for an integration guide

---

bin/build_and_run_jar.sh
extensions/cloud/portability-cloud-google/config/environments/local/settings.yaml
extensions/cloud/portability-cloud-google/config/settings.yaml
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudExtension.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudExtensionModule.java
portability-worker/build.gradle
portability-worker/src/main/java/org/dataportabilityproject/worker/ConfigUtils.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerExtensionContext.java
portability-worker/src/test/java/org/dataportabilityproject/worker/ConfigUtilsTest.java

Make WorkerExtensionContext parse yaml config and expose settings via ExtensionContext.getConfiguration()
ExtensionContext.getConfiguration() is already used in GoogleCloudExtension.
#197

Parse yaml config and expose settings via getConfiguration() in worker

---

bin/build_and_run_jar.sh
distributions/gateway-default/build.gradle

Update build script to build distribution
this can be run now with 
`
$ ./bin/build_and_run_jar.sh gateway local google 
$ ./bin/build_and_run_jar.sh worker local google 
`

Add distribution for portability-gateway

---

.gitignore
extensions/auth/portability-auth-microsoft/src/main/resources/META-INF/services/org.dataportabilityproject.spi.gateway.auth.AuthServiceProvider
extensions/cloud/portability-cloud-google/src/main/resources/META-INF/services/org.dataportabilityproject.spi.cloud.extension.CloudExtension
extensions/data-transfer/portability-data-transfer-microsoft/src/main/resources/META-INF/services/org.dataportabilityproject.spi.transfer.extension.TransferExtension
portability-gateway/src/main/java/org/dataportabilityproject/gateway/ApiMain.java

This allows them to be available to the service loader #208

Declare services implemented in extensions

---

portability-worker/build.gradle
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerMain.java
settings.gradle

User serviceLoader for loading the CloudExtension in worker-main

---

extensions/auth/portability-auth-microsoft/src/main/java/org/dataportabilityproject/auth/microsoft/MicrosoftAuthServiceExtension.java
extensions/auth/portability-auth-microsoft/src/main/resources/META-INF/services/org.dataportabilityproject.spi.gateway.auth.AuthServiceProvider
extensions/auth/portability-auth-microsoft/src/main/resources/META-INF/services/org.dataportabilityproject.spi.gateway.auth.extension.AuthServiceExtension
portability-gateway/src/main/java/org/dataportabilityproject/gateway/PortabilityAuthServiceProviderModule.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/PortabilityAuthServiceProviderRegistry.java
portability-gateway/src/test/java/org/dataportabilityproject/spi/gateway/auth/PortabilityAuthServiceExtensionRegistryTest.java
portability-spi-gateway/src/main/java/org/dataportabilityproject/spi/gateway/auth/AuthServiceProviderRegistry.java
portability-spi-gateway/src/main/java/org/dataportabilityproject/spi/gateway/auth/extension/AuthServiceExtension.java
portability-spi-gateway/src/main/java/org/dataportabilityproject/spi/gateway/extension/GatewayExtension.java

Rename AuthServiceProvider -> AuthServiceExtension which extends AbstractExtension

---

portability-worker/build.gradle
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerMain.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerModule.java

 Load TransferExtensions from ServiceLoader instead of hardcoding

---

extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleAppCredentialStore.java

Followup from code review in PR #243

Minor clean up fixes

---

extensions/auth/portability-auth-google/build.gradle
extensions/auth/portability-auth-google/src/main/java/org/dataportabilityproject/auth/google/GoogleAuthDataGenerator.java
extensions/auth/portability-auth-google/src/test/java/org/dataportabilityproject/auth/google/GoogleAuthDataGeneratorTest.java

fix scopes requested in portability-auth-google

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/contacts/GoogleContactsExporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/MicrosoftTransferExtension.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/action/createjob/CreateJobAction.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/DataTransferHandler.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/Oauth2CallbackHandler.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/OauthCallbackHandler.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/SetupHandler.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/SimpleLoginSubmitHandler.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/JobAuthorization.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/PortabilityJob.java
portability-spi-cloud/src/test/java/org/dataportabilityproject/spi/cloud/types/PortabilityJobTest.java
portability-worker/src/main/java/org/dataportabilityproject/worker/JobProcessor.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerExtensionContext.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerModule.java
portability-worker/src/test/java/org/dataportabilityproject/worker/JobPollingServiceTest.java

Fix bindings for auth data types in type manager, and add session key decryption to the worker

Fixes auth data deserialization in the worker

---

distributions/demo-server/build.gradle
extensions/cloud/portability-cloud-local/src/main/java/org/dataportabilityproject/cloud/local/LocalJobStore.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/contacts/GoogleContactsExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/contacts/GoogleContactsImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/MicrosoftTransferExtension.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/calendar/MicrosoftCalendarExporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/calendar/MicrosoftCalendarImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/common/RequestHelper.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/contacts/MicrosoftContactsExporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/contacts/MicrosoftContactsImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/dataportabilityproject/transfer/microsoft/integration/MicrosoftCalendarImportTest.java
portability-bootstrap-vm/src/main/java/org/dataportabilityproject/bootstrap/vm/SingleVMMain.java
portability-core/src/main/java/org/dataportabilityproject/serviceProviders/google/contacts/VCardToGoogleContactConverter.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/action/startjob/StartJobAction.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/ReferenceApiUtils.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/PortabilityJob.java
portability-worker/src/main/java/org/dataportabilityproject/worker/JobMetadata.java
portability-worker/src/main/java/org/dataportabilityproject/worker/JobProcessor.java

This fixes a bunch of issues to get the end-to-end demo of contacts transfer working.

Demo server fixes

---

portability-gateway/src/main/java/org/dataportabilityproject/gateway/PortabilityAuthServiceProviderRegistry.java

Previous this returned all the services whether they offered that data type or not.

Small bug fix: Return services corresponding to transferDataType in getServices().

---

extensions/auth/portability-auth-google/build.gradle
extensions/auth/portability-auth-google/src/main/java/org/dataportabilityproject/auth/google/GoogleAuthDataGenerator.java
extensions/auth/portability-auth-google/src/main/java/org/dataportabilityproject/auth/google/GoogleAuthServiceExtension.java
extensions/auth/portability-auth-google/src/test/java/org/dataportabilityproject/auth/google/GoogleAuthDataGeneratorTest.java
extensions/data-transfer/portability-data-transfer-google/build.gradle
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/tasks/GoogleTasksExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/tasks/GoogleTasksImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/dataportabilityproject/datatransfer/google/tasks/GoogleTasksExporterTest.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/types/TempTasksData.java

Google tasks

---

extensions/cloud/portability-cloud-microsoft/build.gradle
extensions/cloud/portability-cloud-microsoft/src/main/java/org/dataportabilityproject/cloud/microsoft/cosmos/AzureKeyVaultStore.java
extensions/cloud/portability-cloud-microsoft/src/main/java/org/dataportabilityproject/cloud/microsoft/cosmos/CosmosStoreInitializer.java
extensions/cloud/portability-cloud-microsoft/src/main/java/org/dataportabilityproject/cloud/microsoft/cosmos/MicrosoftCloudExtension.java
extensions/cloud/portability-cloud-microsoft/src/main/resources/META-INF/services/Users/jim/workspace/metaform/microsoft/data-portability/extensions/cloud/portability-cloud-google/src/main/resources/META-INF/services/org.dataportabilityproject.spi.cloud.extension.CloudExtension
gradle.properties

Work in progress on getting to run in Azure...

Add in Azure Vault for secrets

---

extensions/auth/portability-auth-google/src/main/java/org/dataportabilityproject/auth/google/GoogleAuthDataGenerator.java
extensions/auth/portability-auth-google/src/main/java/org/dataportabilityproject/auth/google/GoogleAuthServiceExtension.java
extensions/auth/portability-auth-google/src/test/java/org/dataportabilityproject/auth/google/GoogleAuthDataGeneratorTest.java

limit scopes requested in Google Auth

---

extensions/auth/portability-auth-harness-microsoft/src/main/java/org/dataportabilityproject/auth/microsoft/harness/AuthTestDriver.java
extensions/auth/portability-auth-microsoft/src/main/java/org/dataportabilityproject/auth/microsoft/MicrosoftAuthDataGenerator.java
extensions/auth/portability-auth-microsoft/src/main/java/org/dataportabilityproject/auth/microsoft/MicrosoftAuthServiceExtension.java

limit oauth scopes requested in microsoft

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/dataportabilityproject/datatransfer/flickr/photos/FlickrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-flickr/src/test/java/org/dataportabilityproject/datatransfer/flickr/photos/FlickrPhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/photos/GooglePhotosImporter.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/types/TempPhotosData.java
portability-worker/src/main/java/org/dataportabilityproject/worker/PortabilityInMemoryDataCopier.java

Tested with Google Photos -> Flickr and Flickr -> Google Photos 
* Enable photos in GoogleAuthServiceExtension
* Enable photos in the GoogleTransferExtension 
* Use getEntries() instead of getAlbumEntries() - getAlbumEntries returns an empty list because of reasons. `¯\_(ツ)_/¯` 
* Google Photos Albums aren't really working as expected so album key lookup is off, instead of looking up album ID, just use the default one.
* Check for nullness in the import data in flickr (which can happen if theres no data to import) 
* Check for Error imports in copier
#213 #210

wire up Google Photos

---

README.md

Updated to more correctly named group alias and minor wording clarifications.

Updated ReadMe with renamed group alias

---

extensions/data-transfer/portability-data-transfer-rememberthemilk/src/main/java/org/dataportabilityproject/transfer/rememberthemilk/tasks/RememberTheMilkTasksExporter.java

Tested with successful job from Remember the Milk -> Remember the Milk 
There are some bugs with the flow from Google -> Rmbr the milk and from Rmbr the milk -> Google, debugging those and following up in a separate PR. 
#217

fix rmbr the milk exporter, when notes are null, dont access notes data.

---

distributions/demo-server/build.gradle
extensions/auth/portability-auth-google/build.gradle
extensions/auth/portability-auth-google/src/main/java/org/dataportabilityproject/auth/google/GoogleAuthDataGenerator.java
extensions/auth/portability-auth-google/src/main/java/org/dataportabilityproject/auth/google/GoogleAuthServiceExtension.java
extensions/auth/portability-auth-google/src/test/java/org/dataportabilityproject/auth/google/GoogleAuthDataGeneratorTest.java
extensions/data-transfer/portability-data-transfer-google/build.gradle
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/mail/GoogleMailExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/mail/GoogleMailImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/dataportabilityproject/datatransfer/google/mail/GoogleMailExporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/dataportabilityproject/datatransfer/google/mail/GoogleMailImporterTest.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/PortabilityAuthServiceProviderRegistry.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/types/TempMailData.java
portability-worker/src/main/java/org/dataportabilityproject/worker/JobProcessor.java

Migrate and complete the Gmail Exporter and Importer

---

extensions/auth/portability-auth-instagram/build.gradle
extensions/auth/portability-auth-instagram/src/main/java/org/dataportabilityproject/auth/instagram/InstagramAuthDataGenerator.java
extensions/auth/portability-auth-instagram/src/main/java/org/dataportabilityproject/auth/instagram/InstagramAuthServiceExtension.java
extensions/auth/portability-auth-instagram/src/main/resources/META-INF/services/org.dataportabilityproject.spi.auth.extension.AuthServiceExtension
extensions/auth/portability-auth-instagram/src/test/java/org/dataportabilityproject/auth/instagram/InstagramAuthDataGeneratorTest.java
settings.gradle

Initial implementation for Instagram auth #285

Initial implementation for Instagram auth

---

Documentation/Developer.md
client/build.gradle
distributions/demo-server/build.gradle
distributions/demo-server/src/config/client/nginx.conf

Let me know if these changes make sense - I updated the gradle script to use the port 3000 for the webapp so we dont have to change any local yaml files, but if theres strong interest, can change it to 3030.

update documentation and scripts for running web application locally

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-instagram/build.gradle
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/InstagramTransferExtension.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoExporter.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/model/Caption.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/model/ImageData.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/model/ImageObject.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/model/MediaFeedData.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/model/MediaResponse.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/model/Meta.java

Migrate InstagramPhotosExporter.

---

distributions/demo-google-deployment/bin/encrypt_and_upload_secrets.sh
distributions/demo-google-deployment/bin/setup_gke_environment.sh

Update a couple last remaining places in GCP scripts to reflect new directory location
Closes #236

Update a couple last remaining places in GCP scripts

---

distributions/demo-google-deployment/api/build.gradle
distributions/demo-google-deployment/transfer/build.gradle

Copy resources into build/ instead of src/. 

---

distributions/common/k8s/README.md

The cluster name was changed in #325

Update cluster name from worker -> transfer in k8s docs

---

extensions/auth/portability-auth-smugmug/src/main/java/org/dataportabilityproject/auth/smugmug/SmugMugAuth/SmugMugOauthInterface.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/dataportabilityproject/transfer/smugmug/photos/SmugMugInterface.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/dataportabilityproject/transfer/smugmug/photos/SmugMugPhotosImporter.java

Album creation and response come back okay, but I'm currently getting an unauthorized error when trying to upload photos. Playing around with the smugmug upload api some more while I figure out what's going on. 
Weird because the response doesn't come back with any more information (like invalid signature or anything). 
#362

Smugmug: fix album creation error (photo upload still isnt working)

---

distributions/demo-server/build.gradle
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/dataportabilityproject/transfer/smugmug/photos/SmugMugInterface.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/dataportabilityproject/transfer/smugmug/photos/SmugMugPhotosExporter.java

There's still some issues around smugmug import that aren't really clear (updated the details in #362). Removing this from the demo server for now and putting the issue on the backlog. 
- handle empty albums in smugmug export
- fix url in smugmug upload request

disable smugmug from demo server

---

distributions/demo-google-deployment/bin/encrypt_and_upload_secrets.sh

Also added a couple of checks #387

Update script to remove legacy path references

---

extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleAppCredentialStore.java
portability-transfer/src/main/java/org/dataportabilityproject/transfer/JobPollingService.java

Fixes bug where keys pulled by GoogleAppCredentialStore would have a newline appended, causing auth to fail.

Rogue newline fix

---

extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudExtension.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudExtensionModule.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleJobStore.java
extensions/cloud/portability-cloud-google/src/test/java/org/dataportabilityproject/cloud/google/GoogleJobStoreTest.java
extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/dataportabilityproject/datatransfer/flickr/photos/FlickrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/mail/GoogleMailImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/tasks/GoogleTasksImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/calendar/MicrosoftCalendarImporter.java
extensions/data-transfer/portability-data-transfer-rememberthemilk/src/main/java/org/dataportabilityproject/transfer/rememberthemilk/tasks/RememberTheMilkTasksImporter.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/storage/JobStore.java

Google Job Store temp data implementation #384

Google Job Store temp data implementation

---

Documentation/Overview.md

Adding update and more detailed content on the Overview page 

---

Documentation/Developer.md

Add a step to install docker as an initial step.

Add an install docker step to developer.md

---

distributions/demo-server/build.gradle
extensions/auth/portability-auth-derived-demo/build.gradle
extensions/auth/portability-auth-derived-demo/src/main/java/org/dataportabilityproject/auth/derived/DerivedDemoAuthDataGenerator.java
extensions/auth/portability-auth-derived-demo/src/main/java/org/dataportabilityproject/auth/derived/DerivedDemoAuthServiceExtension.java
extensions/auth/portability-auth-derived-demo/src/main/resources/META-INF/services/org.dataportabilityproject.spi.api.auth.extension.AuthServiceExtension
extensions/auth/portability-auth-microsoft/src/main/java/org/dataportabilityproject/auth/microsoft/MicrosoftAuthDataGenerator.java
extensions/auth/portability-auth-microsoft/src/main/java/org/dataportabilityproject/auth/microsoft/MicrosoftAuthServiceExtension.java
extensions/data-transfer/portability-data-transfer-derived-demo/build.gradle
extensions/data-transfer/portability-data-transfer-derived-demo/src/main/java/org/dataportabilityproject/transfer/derived/DerivedDemoImporter.java
extensions/data-transfer/portability-data-transfer-derived-demo/src/main/java/org/dataportabilityproject/transfer/derived/DerivedDemoTransferExtension.java
extensions/data-transfer/portability-data-transfer-derived-demo/src/main/resources/META-INF/services/org.dataportabilityproject.spi.transfer.extension.TransferExtension
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/MicrosoftTransferExtension.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/derived/MicrosoftDerivedDataExporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/spi/types/MicrosoftDerivedData.java
settings.gradle

This adds demo support for transferring derived data.

Add demo support for import/export of derived data

---

client-rest/package-lock.json
client-rest/package.json
settings.gradle

When i was trying to run locally using `ng serve --ssl --port 3000 --proxy-config proxy.conf.json`, the command line instructed me to do this
/shrug

run npm audit fix on client-rest and add the package to project settings

---

Documentation/Developer.md

add some documentation on how to run the client-rest version of the UI

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/photos/GooglePhotosExporter.java

This does NOT retrieve photos that aren't in albums, this just means there won't be an NPE.

Fixing Google Photos NPE on album retrieval

---

Documentation/Overview.md

Said Data Portability Project, should be Data Transfer Project

Update title of Overview.md

---

Documentation/Keys.md

Give a little more detailed guidance on what to do with key info once you acquire it.

Provide some more details in the keys.md file

---

Documentation/Keys.md
Documentation/RunFromDocker.md

This should make it much easier for folks to try out.

Add documentation on how to pull a docker image from Docker Hub

---

client/package-lock.json

According to https://docs.npmjs.com/files/package-lock.json, it is intended to be committed into source repositories, and serves various purposes.
I believe I generated this when I 'npm install'd in my client/ directory when setting up the project on my Mac.

Add package-lock.json

---

Documentation/Developer.md

Add the correct title to match the white paper, the office hours placeholder, and where to start

Update the Developers Guide

---

portability-api/src/test/java/org/datatransferproject/api/auth/PortabilityAuthServiceExtensionRegistryTest.java

Added tests for 
- GetAuthDataGenerator
- GetImportServices
- GetExportServices
- GetTransferDataTypes

Added more tests for PortabilityAuthServiceExtensionRegistry

---

portability-api/src/test/java/org/datatransferproject/api/action/datatype/DataTypesActionTest.java

Test added for following functions
- GetRequestType
- handle

Added tests for DataTypesAction

---

extensions/data-transfer/portability-data-transfer-twitter/Readme.md

Replace "Instagram extension was created..." for "Twitter extension was created..."

Typo error

---

.travis.yml
client-rest/e2e/protractor.conf.js
client-rest/e2e/src/app.e2e-spec.ts
client-rest/e2e/src/app.po.ts
client-rest/package.json
client-rest/src/app/app.component.spec.ts
client-rest/src/app/app.module.ts
client-rest/src/karma.conf.js

All tests has been fixed except one.
Third test has been disabled here https://github.com/google/data-transfer-project/commit/83a330f517732a0d61dc874b6ef069b4abb7ac9b

Fixed AngularJS Test

---

client-rest/src/app/transfer/initiate-transfer.component.ts
client-rest/src/app/types/start-transfer-job.ts
portability-api/src/main/java/org/datatransferproject/api/action/transfer/StartTransferJobAction.java
portability-types-client/src/main/java/org/datatransferproject/types/client/transfer/StartTransferJob.java

Tested a photos transfer with the demo server
Fixes #528

Accept either raw or encrypted creds in API server

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporterTest.java

I think this fixes the issues we were having with Flickr.

Undoing orphan data 'fix' since it broke things

---

distributions/demo-google-deployment/api/build.gradle
distributions/demo-google-deployment/transfer/build.gradle

Necessary for running demo-google-server

Add gradle imports to demo-google-server

---

client-rest/src/app/transfer/create-transfer.component.ts
client-rest/src/app/types/create-transfer-job.ts

Tested a photos transfer in the demo server

Update json field names in the demo frontend to match #545

---

portability-types-client/src/main/java/org/datatransferproject/types/client/transfer/TransferJob.java
portability-types-client/src/test/java/org/datatransferproject/types/client/transfer/TransferJobTest.java

Tested a photos transfer in the demo server

Update field names in CreateTransferJob response

---

client-rest/package.json

This is needed to fix Travis PR build for #535
Tested demo-server locally

Upgrade Angular-cli version to 6.1.4

---

distributions/demo-google-deployment/bin/setup_gke_environment.sh
distributions/demo-google-deployment/transfer/build.gradle

These were copied from #535 which has some unrelated changes we will save for later.

Updates to demo-google-deployment

---

client-rest/src/app/data/data-types.service.ts
client-rest/src/app/transfer/create-transfer.component.ts
client-rest/src/app/transfer/transfer.service.ts
client-rest/src/environments/.gitignore
client-rest/src/environments/environment.prod.ts
client-rest/src/environments/environment.ts

Note: we may want to rename this at a future date to reflect that it is now the "client URL", but leaving as is for now
Tested a photos transfer locally in the demo server.

Consolidate URL flags in client

---

client-rest/package-lock.json
client-rest/package.json
client-rest/src/app/transfer/initiate-transfer.component.ts
client-rest/src/app/types/start-transfer-job.ts
portability-api/src/main/java/org/datatransferproject/api/action/transfer/GenerateServiceAuthDataAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/GetReservedWorkerAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/ReserveWorkerAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/StartTransferJobAction.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/JobAuthorization.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/PortabilityJob.java
portability-transfer/build.gradle
portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java
portability-transfer/src/test/java/org/datatransferproject/transfer/JobPollingServiceTest.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/auth/AuthDataPair.java

This (large) PR refactors credential encryption to be performed by the client UI using the worker's public RSA key and transferring the encrypted credentials as a JSON Web Encryption (JWE) to the API server.
Client-side encryption is performed using a The Square JWE library which is a wrapper around the WebCrypto API.

Client encryption

---

extensions/cloud/portability-cloud-local/src/main/java/org/datatransferproject/cloud/local/LocalJobStore.java
extensions/cloud/portability-cloud-local/src/main/java/org/datatransferproject/cloud/local/LocalTempFileStore.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/JobStore.java

Add a local temp file store, to mirror the GoogleTempFileStore.

Add local store

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosExporter.java
extensions/data-transfer/portability-data-transfer-flickr/src/test/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/datatransferproject/transfer/instagram/photos/InstagramPhotoExporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosExporter.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosExporter.java
extensions/data-transfer/portability-data-transfer-twitter/src/main/java/org/datatransferproject/transfer/twitter/TwitterPhotosExporter.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/models/photos/PhotoModel.java
portability-types-transfer/src/test/java/org/datatransferproject/types/transfer/models/photos/PhotosContainerResourceTest.java

Indicates whether photo is stored in temp storage or not

Adding another field to PhotoModel 

---

client-rest/src/app/start/start.component.ts
extensions/security/portability-security-cleartext/src/main/java/org/datatransferproject/security/cleartext/ClearTextAuthDataDecryptService.java

These were some updates for the last PR feedback

Changes for PR feedback

---

distributions/demo-google-deployment/transfer/build.gradle
distributions/demo-server/src/main/resources/config/transfer.yaml
extensions/config/portability-config-yaml/src/main/java/org/datatransferproject/config/yaml/YamlSettingsExtension.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerMain.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerModule.java
portability-transfer/src/test/java/org/datatransferproject/transfer/JobPollingServiceTest.java

This should leave room for further schedule configuration down the road, should we wish.

Configuring polling frequency

---

client-rest/package-lock.json
client-rest/package.json

updated using npm audit fix command to remove the cryptiles dependency

Update package lock json

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporterTest.java

Fixing Google Photos issue where temp photos data was too big for the job store

Fixing Google Photos

---

portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java

Do not remove job from jobstore upon completion, but set the job state to either COMPLETE or ERROR.

Set job state appropriately after finishing job

---

extensions/auth/portability-auth-facebook/build.gradle
extensions/data-transfer/portability-data-transfer-facebook/build.gradle

We have not been able to verify that this works with JCenter as we didn't run an actual binary upload but it looks in line with the other modules

Publish portability-auth-facebook and portability-data-transfer-facebook

---

libraries/auth/build.gradle

:libraries:auth was missing from Bintray

Publish auth

---

distributions/demo-server/build.gradle
extensions/auth/portability-auth-google/src/main/java/org/datatransferproject/auth/google/BloggerAuthServiceExtension.java
extensions/auth/portability-auth-google/src/main/java/org/datatransferproject/auth/google/BloggerOAuthConfig.java
extensions/auth/portability-auth-google/src/main/java/org/datatransferproject/auth/google/GoogleOAuthConfig.java
extensions/auth/portability-auth-google/src/main/resources/META-INF/services/org.datatransferproject.spi.api.auth.extension.AuthServiceExtension
extensions/data-transfer/portability-data-transfer-google/Readme.md
extensions/data-transfer/portability-data-transfer-google/build.gradle
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/BloggerTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/blogger/GoogleBloggerImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/gplus/GooglePlusExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/resources/META-INF/services/org.datatransferproject.spi.transfer.extension.TransferExtension
extensions/data-transfer/portability-data-transfer-mastodon/src/main/java/org/datatransferproject/transfer/mastodon/model/Status.java
extensions/data-transfer/portability-data-transfer-mastodon/src/main/java/org/datatransferproject/transfer/mastodon/social/MastodonActivityExport.java
gradle.properties

This creates a blogger imported for social data, storing photos in Drive. (This is related to #586)
There are also some related changes around G+ and Mastodon exports.

Add a Blogger importer for Social-Data

---

extensions/data-transfer/portability-data-transfer-facebook/src/main/java/org/datatransferproject/transfer/facebook/photos/FacebookPhotosExporter.java

Realised we hadn't pushed this change to GitHub

Fix FacebookPhotosExporter

---

distributions/demo-google-deployment/api/build.gradle
distributions/demo-google-deployment/transfer/build.gradle
distributions/demo-server/build.gradle
distributions/demo-server/env.secrets.template
extensions/auth/portability-auth-deezer/build.gradle
extensions/auth/portability-auth-deezer/src/main/java/org/datatransferproject/auth/deezer/DeezerAuthServiceExtension.java
extensions/auth/portability-auth-deezer/src/main/java/org/datatransferproject/auth/deezer/DeezerOAuthConfig.java
extensions/auth/portability-auth-deezer/src/main/java/org/datatransferproject/auth/deezer/package-info.java
extensions/auth/portability-auth-deezer/src/main/resources/META-INF/services/org.datatransferproject.spi.api.auth.extension.AuthServiceExtension
extensions/data-transfer/portability-data-transfer-deezer/Readme.md
extensions/data-transfer/portability-data-transfer-deezer/build.gradle
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/DeezerApi.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/DeezerTransferExtension.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/Album.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/Artist.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/Error.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/InsertResponse.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/PlaylistDetails.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/PlaylistSummary.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/PlaylistsResponse.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/Track.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/TrackCollection.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/model/User.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/playlists/DeezerPlaylistExporter.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/playlists/DeezerPlaylistImporter.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/resources/META-INF/services/org.datatransferproject.spi.transfer.extension.TransferExtension
libraries/auth/src/main/java/org/datatransferproject/auth/OAuth2Config.java
libraries/auth/src/main/java/org/datatransferproject/auth/OAuth2DataGenerator.java
libraries/auth/src/main/java/org/datatransferproject/auth/OAuthUtils.java
settings.gradle

Helps with #495
Deezer also does their auth token response a little different so I generified the base logic to hande it.

Create a Deezer playlist importer and exporter

---

portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/PortabilityJob.java

Set JOB_STATE in PortabilityJob toMap() and fromMap()

---

portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/ConsoleMonitor.java
portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/events/EventCode.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/CreateTransferJobAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/GenerateServiceAuthDataAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/GetReservedWorkerAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/GetTransferJobAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/ReserveWorkerAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/StartTransferJobAction.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java

Add event codes which can be picked up by the monitor for job tracking and metrics.
This seems slightly different to Pull Request #675 but we should maybe have a chat to make sure we're not duplicating anything.

Event codes

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporterTest.java

Storing temp photos data as a stream in Google Photos Exporter

---

Documentation/JettyApiSpec.yaml
Documentation/Keys.md
extensions/auth/portability-auth-imgur/src/main/java/org.datatransferproject.auth.imgur/ImgurOAuthConfig.java
extensions/data-transfer/portability-data-transfer-imgur/Readme.md
extensions/data-transfer/portability-data-transfer-imgur/build.gradle
extensions/data-transfer/portability-data-transfer-imgur/src/main/java/org/datatransferproject/datatransfer/imgur/ImgurTransferExtension.java
extensions/data-transfer/portability-data-transfer-imgur/src/main/java/org/datatransferproject/datatransfer/imgur/photos/ImgurPhotosImporter.java

Added Imgur importer ( #641) and documentation.

Imgur importer

---

distributions/demo-server/build.gradle
extensions/cloud/portability-cloud-google/build.gradle
extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleCloudExtensionModule.java
extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/StackdriverMonitor.java
extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/StackdriverMonitorExtension.java
extensions/cloud/portability-cloud-google/src/main/resources/META-INF/services/org.datatransferproject.api.launcher.MonitorExtension
extensions/data-transfer/portability-data-transfer-solid/src/main/java/org/datatransferproject/transfer/solid/SolidUtilities.java
extensions/data-transfer/portability-data-transfer-solid/src/main/java/org/datatransferproject/transfer/solid/contacts/SolidContactsExport.java
gradle.properties
portability-api-launcher/src/main/java/org/datatransferproject/api/launcher/JobAwareMonitor.java
portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/MonitorLoader.java
portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/MultiplexMonitor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/InMemoryIdempotentImportExecutor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java

Provides a GCP implementation for #607.
Also cleans up a couple {} style logging comments to allow for better string formats.

Create a stack driver logging implementation for GCP

---

portability-api/src/main/java/org/datatransferproject/api/ApiMain.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerMain.java

Fixes #686, this was broken by https://github.com/google/data-transfer-project/pull/684

Add an explicit binding for TemporaryPerJobDataStore

---

extensions/cloud/portability-cloud-google/build.gradle
extensions/cloud/portability-cloud-google/gradle.properties
extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleDtpInternalMetricExtension.java
extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleDtpInternalMetricRecorder.java

Setup a Stackdriver metric adapter

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleJobStore.java

Also only update created field when we're creating the entity.
#691

populate LastUpdated field in GoogleJobStore

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleDtpInternalMetricRecorder.java

- duration is in Millis which is a long, so switch to MeasureLong
- description fixes

small metric recording fixes

---

portability-api/src/main/java/org/datatransferproject/api/ApiMain.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerMain.java

Log guice startup errors through monitor. This helps with debugging errors at startup.
Sorry, not sure why the import order changes all of the sudden.

log guice startup errors through monitor

---

build.gradle
extensions/security/portability-security-cleartext/src/main/java/org/datatransferproject/security/cleartext/ClearTextSymmetricKeyGenerator.java
extensions/security/portability-security-jwe/src/main/java/org/datatransferproject/security/jwe/JWESymmetricKeyGenerator.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/security/SecurityExtensionLoader.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/security/TransferKeyGenerator.java
portability-transfer/src/test/java/org/datatransferproject/transfer/JobPollingServiceTest.java

Missed these in the previous PR, #709

Add TransferKeyGenerator related files missing in #709

---

extensions/security/portability-security-jwe/src/main/java/org/datatransferproject/security/jwe/JWEAuthDataDecryptService.java

I had fixed this but it got lost in the merge of #712

Use correct constant

---

.travis.yml
client-rest/src/karma.conf.js

Using xenial and xvfb services per this documentation https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb

Updating xvfb

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/BloggerTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/common/GoogleCredentialFactory.java

so we get a hook into errors that occur during token refresh

GooglePhotosExporter: add a CredentialRefreshListener when creating creds

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java

Encode smugmug payload values

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/contacts/GoogleContactsExporter.java

This PR handles the case when there are multiple primary names. Existing code will consider only one primary name and ignores others (if there are any).

[Fix] Handle case when there are multiple primary names 

---

portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java

Fix NoSuchElement exception in CallableImporter logging

---

.travis.yml

This PR introduces travis check on all PRs. Adding this as the first step in CI Check.
Fixes this https://github.com/google/data-transfer-project/issues/739

Travis check google-java-format on all PRs

---

Documentation/Developer.md

`nvm install node` was installing node 12, which is not compatible with our project. (Something to do with https://github.com/sass/node-sass/issues/2662)

Update documentation to install stable node version

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/common/GoogleCredentialFactory.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java

the refreshToken() call in the credential library swallows the exception that occurs in favor of propagating up through the refresh listeners. But it looks like the listener we have hooked up isnt properly working so for now, just perform the update manually.
I also formatted this directory with google-java-format #739

Refresh oauth credential manually (outside of the credential) to get better insight into why the update failed

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosImporter.java

How do y'all feel about what the name of this album should be? I wasn't sure if we wanted it to be "Photos transferred from SRC on DATE" or whatever.
@holachuy @seehamrun  lmk what you think

Create a folder for un-foldered photos in the smugmug importer

---

extensions/auth/portability-auth-google/src/main/java/org/datatransferproject/auth/google/GoogleOAuthConfig.java

see https://developers.google.com/identity/protocols/OAuth2WebServer#creatingclient

Update GoogleOauthConfig to use new prompt url param

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java

We were seeing HTTP 400 Bad Request errors for photos with long descriptions.

Trim photo description and album title if too long.

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java

Adds the content of an HTTPResponseException to the IOException thrown as it was difficult to debug the root cause without the content.

Add http response content to exception in GooglePhotosInterface

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java

Return correct photo ID in ms photo importer

---

Documentation/RunningLocally.md

Addresses https://github.com/google/data-transfer-project/issues/783

Update RunningLocally.md to use latest /datatypes URL

---

portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryingCallable.java

We will still log at severe if we fail after retries but given that there are varies things that can be fixed with a retry it is currently polluted our severe logs to have this at a high level.
If the retry fails then it will be logged in PortabilityInMemoryDataCopier: https://github.com/google/data-transfer-project/blob/870f16223d2a622709a924bffd08c1be115cdf5e/portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java#L171
(Also did google-java-format-1.7)

Reduce log level for exception in RetryingCallable

---

portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/PortabilityJob.java

This may assist with restart scenarios

Add PREEMPTED state

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotosContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/photos/PhotosContainerResourceTest.java

@chuy @seehamrun 
I had a `break` where I needed a `continue`, also I renamed a variable to make more sense.

Fix album splitting error/add test case

---

Documentation/Integration.md
Documentation/Overview.md
extensions/data-transfer/portability-data-transfer-solid/SolidAuthSetup.md

Fix some code blocks. Add language identifier to enable syntax highlighting
Copy of #716

fix code blocks in docs

---

how-does-dtp-work.md

Fix header in docs

---

extensions/data-transfer/portability-data-transfer-twitter/src/main/java/org/datatransferproject/transfer/twitter/TwitterTransferExtension.java

fix copy paste error

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleJobStore.java
extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleTempFileStore.java
extensions/cloud/portability-cloud-local/src/main/java/org/datatransferproject/cloud/local/LocalJobStore.java
extensions/cloud/portability-cloud-local/src/main/java/org/datatransferproject/cloud/local/LocalTempFileStore.java
extensions/cloud/portability-cloud-microsoft/src/main/java/org/datatransferproject/cloud/microsoft/cosmos/AzureTableStore.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/blogger/GoogleBloggerImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/drive/DriveImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-imgur/src/main/java/org/datatransferproject/datatransfer/imgur/photos/ImgurPhotosImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/helper/MockJobStore.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosImporter.java
libraries/transfer/src/main/java/org/datatransferproject/transfer/ImageStreamProvider.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/JobStore.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/TemporaryPerJobDataStore.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/provider/ImportResult.java
portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java

This includes a google-java-format-1.7 commit so to just see the meaningful changes you can isolate to https://github.com/google/data-transfer-project/commit/56ef12f459ccfc8acfac5186655b82905de531e5

Count bytes transferred in photos and videos transfers

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/PhotoResult.java

Otherwise we can get NullPointerExceptions when trying to add.

Make sure the PhotoResult does not have a null bytes value

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/IdempotentImportExecutor.java

executeAndSwallowIOExceptions can return null. Added annotations and checks

Additional checks for nulls

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/CopyExceptionWithFailureReason.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/DestinationMemoryFullException.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/FailureReasons.java

This includes the suggestions from @holachuy

Add javadoc and move failure reason to enum.

---

portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java

We want to compare classes rather than check an object. I have fully tested this to verify it works as expected. JavaDoc of method here https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#isAssignableFrom-java.lang.Class-

Correct how we check the class of the exception

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransferExtension.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransmogrificationConfig.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosExporter.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosImporter.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/model/SmugMugAlbum.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/model/SmugMugAlbumImageResponse.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/model/SmugMugAlbumInfoResponse.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/model/SmugMugAlbumsResponse.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/model/SmugMugImage.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/model/SmugMugImageUploadResponse.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/model/SmugMugUser.java
extensions/data-transfer/portability-data-transfer-smugmug/src/test/java/org/datatransfer/smugmug/photos/SmugMugInterfaceTest.java

To see changes made after the format: https://github.com/google/data-transfer-project/pull/855/commits/a796a93e993574d377928ec9dd141bcadb8f95c8

Reformat Smugmug directory to follow google_java_format and remove transport as an unused field

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotoTempData.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosImporter.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/model/SmugMugImageUploadResponse.java

This encompasses a fix on the serialization definition of SmugMugPhotoTempData and SmugMugImageUploadResponse that allows the jobstore and the interface read data correctly.

Smugmug fix

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java

Handle errors like the following: 
```
Problem with importing item: ErrorDetail{id=XXX, title=XXX, exception=java.io.IOException: Got error code: 403 message: Forbidden body: {
"error": {
"code": "accessDenied",
"message": "Access Denied",
"innerError": {
"request-id": "XXX",
"date": "XXX"
}
}
```
Note: while writing this PR, i also noticed that the credential being stored in a member variable. This has been discussed in depth in #882 see [discussion](https://github.com/google/data-transfer-project/pull/882#discussion_r424538895) and I will send a followup change to switch this to being stored in either a map or retrieved per request. Unless we change the interface to be per job/authdata pair we shouldnt store job specific member variables.

Handle AccessDenied exception in MicrosoftPhotosImporter

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java

Summary:
GoogleVideosImporter is leaking memory because
1) It creates a PhotosLibraryClient every time it imports a video
2) PhotosLibraryClient would create a bunch of worker Gax threads
3) PhotosLibraryClient would not clean up those threads when it finishes
This resuls in OOM issue when transferring large videos jobs.
This commit is to fix this OOM issue by reusing same PhotosLibraryClient
for the same job. So worker is not wasting cpu and memory to create new
threads for each video.
Test Plan:
Transfer many videos in one job and confirm that threads count will not
increase.

Fix OOM issue for video task

---

extensions/auth/portability-auth-facebook/src/main/java/org/datatransferproject/auth/facebook/FacebookOAuthConfig.java

This was missed on the previous pull request

Add video to FacebookOAuthConfig

---

portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java

Summary:
When the importer returns errors after importItem call. The metrics
logging would still record it as success.
This commit is to fix that.
Test Plan: Do a transfer and check the metric logging on importPageAttemptFinished

Fix success logging in importPageAttemptFinished

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporterTest.java

Summary: Batch video creation request.
Test Plan: Ran a video transfer with the docker container

Add Google video batching

---

Documentation/JettyApiSpec.yaml
build.gradle
client-rest/build.gradle
extensions/auth/portability-auth-facebook/build.gradle
extensions/auth/portability-auth-google/build.gradle
extensions/auth/portability-auth-instagram/build.gradle
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/drive/DriveImporter.java
libraries/config/src/main/java/org/datatransferproject/config/FlagBindingModule.java
libraries/security/build.gradle
portability-api/src/main/java/org/datatransferproject/api/action/transfer/GenerateServiceAuthDataAction.java
portability-spi-service/src/main/java/org/datatransferproject/spi/service/extension/ServiceExtension.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/auth/CookiesAndUrlAuthData.java

While looking at the source code I found some minor things that bugged/confused me. This is a PR to fix them.

Various minor fixes

---

extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/KoofrTransferExtension.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/common/ApiErrorDetails.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/common/FilesFile.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/common/FilesListRecursiveItem.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/common/KoofrClient.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/common/KoofrClientFactory.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/common/KoofrMediaExport.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/photos/KoofrPhotosExporter.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosExporter.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/common/Fixtures.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/common/KoofrClientTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/photos/KoofrPhotosExporterTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosExporterTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/resources/listrecursive.jsonl
portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotoAlbum.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideoAlbum.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideoObject.java

This is a first version of Photos and Videos export. It does not use pagination because Koofr's API does not support it.
Closes #933

Implement KoofrPhotosExporter and KoofrVideosExporter

---

portability-bootstrap-vm/src/main/java/org/datatransferproject/bootstrap/vm/SingleVMMain.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/copier/PortabilityAbstractInMemoryDataCopier.java

Summary:
Move the exception severe logging to the seperate parameter. So it can
be better displayed and parsed by logging framework.
Test Plan: Built/tested/loglined
Reviewers: #dtp
Subscribers:
Tasks: T81987523
Tags:
Blame Revision:
Differential Revision: https://phabricator.intern.facebook.com/D25824059

Imrpove severe logging with exception in seperate parameter

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotosContainerResource.java

Add toString method to PhotosContainerResource

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java

If the exporter being used for the job put the photo into the temp store, the Flickr importer wouldn't use it.

Update FlickrPhotosImporter to use temp store as needed

---

Documentation/JettyApiSpec.yaml

- Fix the URL and request body for start requests
- Update capitalization in example services request to better match the values returned

Updates to OpenApi spec

---

Documentation/Keys.md
extensions/data-transfer/portability-data-transfer-facebook/Readme.md

Added a README for Facebook extension, listing how to get keys and any other support. Also linked it from the Keys page in documentation.

Updating developer documentation for Facebook

---

.github/workflows/gradle.yml

Use the gradle.yml file to kick off a gradle build and test

Reintroduce CI w/ Github Actions

---

extensions/data-transfer/portability-data-transfer-backblaze/build.gradle
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/BackblazeTransferExtension.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClient.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClientFactory.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeS3ClientFactory.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/common/BaseBackblazeS3ClientFactory.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporter.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporter.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClientTest.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/resources/test.txt

In this series of commits I'm updating Backblaze extension classes to enable unit testing. The first two commits contain changes to the photo importer (constructor refactoring + unit tests), the next two contain changes to the video importer (constructor refactoring + unit tests) and the last three are about refactoring the client (extracting the S3 client factory, refactoring the client and unit tests).

Backblaze refactor

---

gradle.properties

Version number

---

.github/workflows/codeql-analysis.yml
Documentation/Developer.md
Documentation/Publishing.md

Instructions for publishing to Maven Central

Add publication instructions

---

gradle.properties

Increasing version for the new release.

increasing patch version

---

extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporter.java

If a URL hit FNF exception then the data has been deleted and we should skip rather than retrying or failing. This is based on how both Google and Koofr handle this exception in their adapters.
As we introduce detailed transfers we may move to marking these items specifically as skipped which can then be surfaced to users

Handle Backblaze FileNotFoundException for videos

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java

Doing in the same way we already do in GoogleCredentialFactory.java by throwing an InvalidTokenException

Handle invalid_grant for videos

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/StackdriverMonitorExtension.java
extensions/transport/portability-transport-jettyrest/src/main/java/org/datatransferproject/transport/jettyrest/rest/JerseyTransportBinder.java
libraries/security/src/main/java/org/datatransferproject/security/DecrypterImpl.java
libraries/security/src/main/java/org/datatransferproject/security/EncrypterImpl.java
portability-api/src/main/java/org/datatransferproject/api/ApiMain.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/CreateTransferJobAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/GenerateServiceAuthDataAction.java
portability-api/src/main/java/org/datatransferproject/api/token/JWTTokenManager.java

For better user experience thrown RuntimeExceptions are extended with messages

Add message to thrown RuntimeExceptions 

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/calendar/CalendarContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/calendar/CalendarContainerResourceTest.java

getCounts has been added to CalendarContainerResource and test updated.

Implement getCounts in CalendarContainerResource

---

extensions/copier/portability-stack-copier/src/main/java/org/datatransferproject/copier/stack/PortabilityStackInMemoryDataCopier.java
portability-transfer/src/main/java/org/datatransferproject/transfer/copier/PortabilityAbstractInMemoryDataCopier.java

No new features or business logic changes, just refactorings. I am planning some changes to DataCopier, so wanted to make it slightly cleaner first.

Cleaner data copier code

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/CachingExecutor.java

Follows the changes I introduced in https://github.com/google/data-transfer-project/pull/1079.

Fix outdated javadoc

---

build.gradle

Follow up on https://github.com/google/data-transfer-project/pull/1114

Fix source compatibility gradle param

---

extensions/cloud/portability-cloud-google/src/test/java/org/datatransferproject/cloud/google/GoogleJobStoreTest.java
extensions/config/portability-config-yaml/src/test/java/org/datatransferproject/config/yaml/YamlSettingsExtensionTest.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClientTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/mail/GoogleMailImporterTest.java
extensions/data-transfer/portability-data-transfer-instagram/src/test/java/org/datatransferproject/transfer/instagram/photos/InstagramPhotoExporterTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/photos/KoofrPhotosExporterTest.java
portability-transfer/src/test/java/org/datatransferproject/transfer/JobPollingServiceTest.java
portability-transfer/src/test/java/org/datatransferproject/transfer/WorkerModuleTest.java

* Migrated from Runners to Extensions (@RunWith -> @ExtendWith)
* Migrated @Test annotations from Junit 4 -> 5
* Migrated @Before & @After to @beforeeach & @AfterEach, @BeforeClass to @BeforeAll

Junit Migration: Upgraded runner to extension

---

portability-transfer/src/test/java/org/datatransferproject/transfer/copier/PortabilityInMemoryDataCopierTest.java

Migrated Parameterized runnner to parameterized test, since there's no class level support from Junit5+, with @MethodSource referencing the static parameter method.

Migrate parameterized JUnit test to Junit5

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/social/SocialActivityAttachment.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/social/SocialActivityModel.java

Updated SocialActivityAttachment and SocialActivityModel classes to implement ImportableItem class

Updated SocialActivityAttachment and SocialActivityModel classes to implement ImportableItem class

---

gradle.properties

This includes the necessary version bumps for switching to numbered Major releases

Release v1.0.0

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/FlickrTransferExtension.java
extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java

no-op change, will make changes to retry strategy in next PR

Add flag guarded retrying idempotent executor to flickr importer

---

portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/errors/ErrorDetail.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryException.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryStrategy.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryingCallable.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/SkipRetryStrategy.java

Add skipRetryStrategy to RetryLibrary and necessary changes to logic of retryingCallable to allow errors to be skipped

Add skipRetryStrategy to RetryLibrary

---

gradle.properties

https://github.com/google/data-transfer-project/releases/tag/v1.0.2

chore: bump version to v1.0.2

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/media/GoogleMediaImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/media/GoogleMediaImporterTest.java

I know GoogleMediaImporter isn't being used, but I am running it locally for testing and this error occurs with all videos.

Refactored GoogleMediaImporter to include the GoogleVideosImporter implementation of PhotosLibraryClient, current implementation always null

---

client-rest/package-lock.json
client-rest/package.json

This is primarily to resolve vulnerabilities in socket.io

Upgrade karma to 6.4.2

---

extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/mediaModels/GoogleMediaItemTest.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/PortabilityJob.java

Needed to customize folder names on the destination sides.
`./gradlew build test`

feat: add userAlias field to PortabilityJob class

---

CONTRIBUTING.md
README.md

Updating the link of master branch to dtinit URL

Update README.md and CONTRIBUTING

---

extensions/security/portability-security-jwe/build.gradle

fix: upgrade nimbus-jose-jwt to 9.21.1

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/MicrosoftTransferExtension.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaImporterTest.java

fix(microsoft) reset http okhttp client when refreshing tokens in case keep-alive is biting us

fix: microsoft speculative client-reset, when token-refresh

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java

factors out the common HTTP logic to a middle-tier private func `makeHttpRequest` to get to a _mostly_ noop cleanup/DRYing of our HTTP handling. (motivation: some issues we're debugging). Things that prevent this from being just a true **noop** refactor:
- `makePostRequest` used to only respect its users' request for special HTTP headers on the _first_ request, but not on subsequent (token-refresh driven) requests. Now it'll respect it for all requests.
- similar to previous point: _rate limiting_ wasn't consistently applied, now it's always applied for every write request, and not just the first.
- similarly, check for HTTP 200 was only done on some request paths, now it's always done; it's also now a consistent stack trace that will hopefully be more useful (like the other stack traces …

fix: googphotos http request handling to be self-consistent

---

extensions/data-transfer/portability-data-transfer-generic/src/main/java/org/datatransferproject/datatransfer/generic/BlobIdToName.java
extensions/data-transfer/portability-data-transfer-generic/src/main/java/org/datatransferproject/datatransfer/generic/BlobbySerializer.java
extensions/data-transfer/portability-data-transfer-generic/src/test/java/org/datatransferproject/datatransfer/generic/BlobIdToNameTest.java
extensions/data-transfer/portability-data-transfer-generic/src/test/java/org/datatransferproject/datatransfer/generic/BlobbySerializerSimulationTest.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/provider/TransferCompatibilityProvider.java

Make BlobIdToName serialisable

fix(generic): Make BlobIdToName serialisable
