dtinit/data-transfer-project

README.md

I'm thinking we want to use the portability-discuss group for open discussion and reserve maintainers for internal team coordination? Thoughts?

Add link to discussion group

---

portability-api/src/main/java/org/dataportabilityproject/webapp/PortabilityApiUtils.java

The way HttpCookie.toString() formats the path is incorrect and doesn't get parsed by the browser which in turn causes some cookies to not be attached to subsequent API requests (ex: encrypted flow tokens set by /callback* handler.

Add path manually to COOKIE_Attributes. 

---

portability-api/src/main/java/org/dataportabilityproject/webapp/ConfigureHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/CryptoHelper.java
portability-api/src/main/java/org/dataportabilityproject/webapp/Oauth2CallbackHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/OauthCallbackHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/PortabilityApiUtils.java
portability-api/src/main/java/org/dataportabilityproject/webapp/SetupHandler.java
portability-api/src/main/java/org/dataportabilityproject/webapp/SimpleLoginSubmitHandler.java
portability-core/src/main/java/org/dataportabilityproject/job/JobUtils.java
portability-core/src/main/java/org/dataportabilityproject/shared/ServiceMode.java
portability-core/src/test/java/org/dataportabilityproject/job/JobUtilsTest.java

This is in prep for limiting Oauth scopes #25  - idea is in addition to passing dataType to serviceProviderRegistry.getOnlineAuthDataGenerator, we would pass in the service mode.  Then each service provider can determine what generator to return based on the pair.

Add ServiceMode enum for passing around instead of boolean isExport.

---

portability-core/src/main/java/org/dataportabilityproject/serviceProviders/instagram/InstagramServiceProvider.java

(Instagram currently only supports IMPORT mode so this is functionally a
no-op). #25

Update InstagramServiceProvider to return auth based on serviceMode.

---

portability-core/src/main/java/org/dataportabilityproject/serviceProviders/google/GoogleServiceProvider.java

For changes introduced in #60 #25 
- Make private members final and static.
- Use ListMultiMap instead of Map.
- Check dataType is valid before creating or retrieving auth.

Slight refactor to make GoogleServiceProvider more similar to MicrosoftServiceProvider.

---

portability-core/src/main/java/org/dataportabilityproject/serviceProviders/flickr/FlickrServiceProvider.java

#25 
- Make private members final static
- Instantiate authGenerators only upon request
- Check dataType is valid before creating or retrieving auth.

Slight refactor to make FlickrServiceProvider more like other Oauth1 providers (Smugmug and RememberTheMilk).

---

client/karma.conf.js

Do not pull yet; testing on Travis with a lower timeout first to make sure it is the correct flag

Increase timeout for Karma to receive activity from Chrome

---

portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/provider/Exporter.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/types/ContinuationData.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/types/ExportInformation.java
portability-types-transfer/src/main/java/org/dataportabilityproject/types/transfer/models/ContainerResource.java

Using ContinuationData as the input to the export call doesn't work because you then don't know which resource to apply the continuation data to.
So a call to export need to take 0 or 1 resources and 0 or 1 continuation tokens, which is now represented in ExportInformation

Re add in ExportInformation

---

extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudDatastore.java

This returns the job ID from the key rather than the value (Entity).
This is necessary so we can remove job ID being stored as part of PortabilityJob in JobStore. This was one place that relied on job ID being stored as part of the job (e.g. Entity).
Tested locally with local Datastore emulator with encryptedFlow=true so we test the worker polling
More on Datastore key queries: https://cloud.google.com/datastore/docs/concepts/queries#keys-only_queries

Use a key query in Datastore for polling

---

bin/build_and_run_jar.sh
config/gcp/build_and_upload_docker_image.sh

1. Use a clean build when building a jar
2. Copy the correct jar into our Docker images. We were still copying the old Maven jars.

Fix a couple deployment-related issues

---

extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudDatastore.java

This fixes our QA deployment which was broken by https://github.com/google/data-portability/pull/117 (which worked fine with the local Datastore emulator but real Datastore required an index for it, which we don't have set up)

Stop trying to order Datastore query by creation time

---

extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudDatastore.java

I know we are about ready to move away from legacy flow, but might as well fix this

Prevent error checking missing property JobState for legacy non-encryption flow

---

extensions/cloud/portability-cloud-microsoft/src/main/java/org/dataportabilityproject/cloud/microsoft/cosmos/CosmosStore.java

It is still referenced in the old code. for #132.

Remove last usage of LegacyPortabilityJob in the new code.

---

Documentation/Developer.md
portability-spi-cloud/build.gradle
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/JobAuthorization.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/PortabilityJob.java

With this change, IntelliJ build now works without any manual adding of source roots. Invalidate caches + restart still works as well.
PortabilityJobTest still runs as well, with the test root added in build.gradle.
I think something is still slightly off with a conflict between the declared package for org.dataportabilityproject.spi.cloud.types.AutoValue_PortabilityJob and the directory structure which includes an extra main/. However, this does not affect the IntelliJ build and is only noticeable if you go into an AutoValue generated impl class.

Fix Intellij issue so we don't have to manually add generated source roots

---

extensions/cloud/portability-cloud-google/build.gradle
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleBucketStore.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudModule.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCredentialException.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCryptoKeyStore.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleJobStore.java
extensions/cloud/portability-cloud-google/src/test/java/org/dataportabilityproject/cloud/google/GoogleCloudModuleTest.java
extensions/cloud/portability-cloud-local/src/main/java/org/dataportabilityproject/cloud/local/LocalJobStore.java
gradle/wrapper/gradle-wrapper.properties
portability-core/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudFactory.java
portability-core/src/main/java/org/dataportabilityproject/cloud/local/LocalCloudFactory.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/storage/BucketStore.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/storage/CryptoKeyStore.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/storage/JobStore.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/types/JobAuthorization.java
portability-worker/src/test/java/org/dataportabilityproject/worker/JobPollingServiceTest.java

 Port Google Cloud classes to the new structure

---

extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleJobStore.java
extensions/cloud/portability-cloud-local/src/main/java/org/dataportabilityproject/cloud/local/LocalJobStore.java
extensions/cloud/portability-cloud-microsoft/src/main/java/org/dataportabilityproject/cloud/microsoft/cosmos/CosmosStore.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/dataportabilityproject/transfer/microsoft/helper/MockJobStore.java
portability-api/src/main/java/org/dataportabilityproject/webapp/StartCopyHandler.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/storage/JobStore.java
portability-worker/src/main/java/org/dataportabilityproject/worker/JobPollingService.java

If we go with this approach, I put a placeholder in the Cosmos Store to implement this

Reintroduce worker race condition fix from #98 that was lost during the migration

---

Documentation/Developer.md

This is apparently not the default all the time - my latest install of
IntelliJ on my new remote machine needed this to be specified.

Document setting for annotation processor sources dir

---

extensions/cloud/portability-cloud-google/build.gradle
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudExtension.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCryptoKeyStore.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/extension/CloudExtension.java

I added getCryptoKeyStore and getBucketStore to the CloudExtension since I suspect they might be needed (the CloudFactory had these). 
I'm not sure of where the initialization of the constructor params should go. My initial thought was to pull them in from the ExtensionContext, but its not clear to me what that looks like for things like creds or the json factories. 
#192

Implementation of GoogleCloudExtensions

---

config/gcp/build_and_upload_docker_image.sh
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleBucketStore.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudExtension.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudExtensionModule.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudModule.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleCryptoKeyStore.java
extensions/cloud/portability-cloud-google/src/main/java/org/dataportabilityproject/cloud/google/GoogleJobStore.java
extensions/cloud/portability-cloud-google/src/test/java/org/dataportabilityproject/cloud/google/GoogleCloudModuleTest.java
libraries/security/src/main/java/org/dataportabilityproject/security/RsaSymmetricKeyGenerator.java
portability-api-launcher/src/main/java/org/dataportabilityproject/api/launcher/ExtensionContext.java
portability-core/src/main/java/org/dataportabilityproject/cloud/google/GoogleBucketStore.java
portability-core/src/main/java/org/dataportabilityproject/cloud/google/GoogleCloudFactory.java
portability-core/src/main/java/org/dataportabilityproject/cloud/google/GoogleCryptoKeyManagementSystem.java
portability-spi-cloud/build.gradle
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/extension/CloudExtension.java
portability-spi-cloud/src/main/java/org/dataportabilityproject/spi/cloud/extension/CloudExtensionModule.java
portability-worker/build.gradle
portability-worker/src/main/java/org/dataportabilityproject/worker/JobPollingService.java
portability-worker/src/main/java/org/dataportabilityproject/worker/PortabilityInMemoryDataCopier.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerExtensionContext.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerMain.java
portability-worker/src/main/java/org/dataportabilityproject/worker/WorkerModule.java

Tested running the worker with the Google cloud extension, with our build/run docker script (in config/gcp/)
Currently the Google cloud extension and Microsoft transfer extension are hardcoded since service loading isn't working yet. I left some TODOs for @seehamrun on service loading the extensions.
Left a TODO for flag parsing as well, currently the worker's ExtensionContext is hardcoded to return local config values
#172

Run worker binary

---

portability-gateway/src/main/java/org/dataportabilityproject/gateway/ApiMain.java

They were being bound as classes, causing Guice to re-instantiate them during injection

Bind auth instances in Guice context

---

portability-gateway/src/main/java/org/dataportabilityproject/gateway/ApiMain.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/JWTTokenManager.java
portability-gateway/src/main/java/org/dataportabilityproject/gateway/reference/ReferenceApiModule.java

#258 (reverts  #266) 
this requires that a JWT_SECRET and JWT_KEY  be provided from the AppCredentialStore.
For local deployment add the following into your ~/.gradle/gradle.properties
```
data.portability.key.jwt=foo
data.portability.secret.jwt=bar
```
For cloud deployment, make sure a file/blob for JWT_KEY and JWT_SECRET exist where the key can contain foo, and the secret should be generated via ssh_keygen or something similar.

 re-enable xsrf protection

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/dataportabilityproject/datatransfer/flickr/photos/FlickrPhotosExporter.java
extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/dataportabilityproject/datatransfer/flickr/photos/FlickrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-flickr/src/test/java/org/dataportabilityproject/datatransfer/flickr/photos/FlickrPhotosExporterTest.java
extensions/data-transfer/portability-data-transfer-flickr/src/test/java/org/dataportabilityproject/datatransfer/flickr/photos/FlickrPhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/calendar/GoogleCalendarExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/calendar/GoogleCalendarImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/contacts/GoogleContactsExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/contacts/GoogleContactsImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/tasks/GoogleTasksExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/dataportabilityproject/datatransfer/google/tasks/GoogleTasksImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/dataportabilityproject/datatransfer/google/calendar/GoogleCalendarExporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/dataportabilityproject/datatransfer/google/calendar/GoogleCalendarImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/dataportabilityproject/datatransfer/google/contacts/GoogleContactsExporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/dataportabilityproject/datatransfer/google/contacts/GoogleContactsImporterTest.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/calendar/MicrosoftCalendarExporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/calendar/MicrosoftCalendarImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/contacts/MicrosoftContactsExporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/dataportabilityproject/transfer/microsoft/contacts/MicrosoftContactsImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/dataportabilityproject/transfer/microsoft/integration/LocalExportTestRunner.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/dataportabilityproject/transfer/microsoft/integration/LocalImportTestRunner.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/dataportabilityproject/transfer/microsoft/integration/MicrosoftCalendarExportTest.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/dataportabilityproject/transfer/microsoft/integration/MicrosoftCalendarImportTest.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/dataportabilityproject/transfer/microsoft/types/TempCalendarDataTest.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/provider/Exporter.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/provider/Importer.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/types/TempCalendarData.java
portability-spi-transfer/src/main/java/org/dataportabilityproject/spi/transfer/types/TempPhotosData.java
portability-worker/src/main/java/org/dataportabilityproject/worker/PortabilityInMemoryDataCopier.java

This PR propagates the Job ID to the exporter which is needed for storing temp data in the JobStore (e.g. for streaming photo content).
This should be applied after #205.

Propagate jobid

---

client/build.gradle

The local build variant that automatically installs node does not work on Ubuntu.
In the meantime, this PR fixes an issue with using the node version that is installed on the host build machine.
From a clean Ubuntu 16.04 image, I installed the following: 
1. Docker
https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04
2. JDK 8 (Make sure to install the JDK, not JRE)
https://www.digitalocean.com/community/tutorials/how-to-install-java-with-apt-get-on-ubuntu-16-04
3. Node global install -follow the section "How To Install Using a PPA"
https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04
4. Angular cli global install
sudo npm install -g @ angular/cli
Then run:
./gradlew -PcloudType=local -PnodeType=host clean check …

Fix for one of the issues running the client build on Ubuntu

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/dataportabilityproject/datatransfer/flickr/photos/FlickrPhotosImporter.java

Note this doesnt fix when the photo is associated to an album, but the album data doesn't exist. It's not clear to me how we should fix this issue. Is it an assumption that we make that all the albums we have are known before we have any photos for it? 
#311

handle case where photo isnt associated to an album at import in flickr

---

distributions/demo-server/build.gradle
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/InstagramTransferExtension.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoExporter.java
extensions/data-transfer/portability-data-transfer-instagram/src/main/java/org/dataportabilityproject/transfer/instagram/photos/InstagramPhotoImporter.java

Small fix & documentation to get Instagram export working in the demo server.
Successfully exported photos from Instagram to Google.
Fixes #285

Small fix & documentation to get Instagram export working

---

portability-api/src/main/java/org/dataportabilityproject/api/PortabilityAuthServiceProviderRegistry.java
portability-api/src/main/java/org/dataportabilityproject/api/action/listservices/ListServicesAction.java
portability-api/src/main/java/org/dataportabilityproject/api/action/listservices/ListServicesActionResponse.java
portability-api/src/main/java/org/dataportabilityproject/api/reference/ListServicesHandler.java
portability-spi-api/src/main/java/org/dataportabilityproject/spi/api/auth/AuthServiceProviderRegistry.java

Import only is NOT supported, and is checked for on creation of the AuthProviderRegistry
#337

split up listServices into listImportServices and listExportServices, to allow for services that want to provide export only.

---

distributions/demo-google-deployment/transfer/build.gradle

This allows the task to build the local transfer tasking running against test GCP to complete

Fix local demo google docker cred copy task

---

distributions/demo-google-deployment/api/build.gradle

Fix copy creds in api gradle file for running locally against GCP test project #392

Fix copy creds in api gradle file for running locally against GCP 

---

portability-transfer/src/main/java/org/dataportabilityproject/transfer/JobPollingService.java

When a worker failed to claim a job, it would throw and exception and die.  This fix updates it so that claiming a job is a matter of success/failure, instead of success/exception, and if a worker fails to claim a job, it can continue to poll.

Fix bug where worker would die after failing to claim a job

---

extensions/cloud/portability-cloud-microsoft/build.gradle

https://mvnrepository.com/artifact/com.microsoft.azure/azure-client-runtime/1.5.4 got pushed out which relies on 1.5.4 of https://mvnrepository.com/artifact/com.microsoft.rest/client-runtime but the 1.5.4 version of that has not been pushed yet, so forcing it to use 1.5.3

Fix a MS build/dependency problem

---

docker_push.sh

docker_push.sh is already in scripts directory (https://github.com/google/data-transfer-project/tree/master/scripts)

Removed redundant script docker_push.sh

---

.travis.yml

Previously, they were passing but didn't actually do anything (#511)
Now they are actually failing the build for #517 so I think they should be disabled so we don't block that PR

Temporarily disable Angular tests until we implement them for client-rest

---

distributions/demo-google-deployment/resources/config/api.yaml
extensions/transport/portability-transport-jettyrest/src/main/java/org/datatransferproject/transport/jettyrest/JettyRestExtension.java
extensions/transport/portability-transport-jettyrest/src/main/java/org/datatransferproject/transport/jettyrest/http/JettyTransport.java

This is necessary for our demo-google-deployment to work with the Jetty transport.
We can't serve HTTPS since don't have certs installed at our API servers; we have them installed at our LB instead.
Keep the default HTTPS for the demo server.

Support serving API requests over HTTP, in addition to HTTPS

---

distributions/demo-google-deployment/transfer/build.gradle

Note: we could include the whole config folder and all yaml files in the environment folders, but I wasn't sure we wanted to do that, given the values in the other yaml files.  The advantage of including all the yaml files is that YamlSettingsExtension will behave as expected, i.e., all the files that are defined (COMMON_SETTINGS_PATH, ENV_API_SETTINGS_PATH, etc) will actually be read.  Only including a subset of the files in the jar makes it hard to understand what's happening.

Allow retry library to be read in by including it in the jar

---

client-rest/src/app/transfer/auth-callback.component.ts
client-rest/src/app/transfer/create-transfer.component.ts
client-rest/src/app/types/create-transfer-job.ts
client-rest/src/app/types/generate-service-auth-data.ts
extensions/auth/portability-auth-flickr/src/main/java/org/datatransferproject/auth/flickr/FlickrAuthDataGenerator.java
extensions/auth/portability-auth-google/src/main/java/org/datatransferproject/auth/google/GoogleAuthDataGenerator.java
extensions/auth/portability-auth-google/src/main/java/org/datatransferproject/auth/google/GoogleAuthServiceExtension.java
extensions/auth/portability-auth-google/src/test/java/org/datatransferproject/auth/google/GoogleAuthDataGeneratorTest.java
extensions/auth/portability-auth-harness-microsoft/src/main/java/org/datatransferproject/auth/microsoft/harness/AuthTestDriver.java
extensions/auth/portability-auth-instagram/src/main/java/org/datatransferproject/auth/instagram/InstagramAuthDataGenerator.java
extensions/auth/portability-auth-instagram/src/test/java/org/datatransferproject/auth/instagram/InstagramAuthDataGeneratorTest.java
extensions/auth/portability-auth-microsoft/src/main/java/org/datatransferproject/auth/microsoft/MicrosoftAuthDataGenerator.java
extensions/auth/portability-auth-microsoft/src/main/java/org/datatransferproject/auth/microsoft/MicrosoftAuthServiceExtension.java
extensions/auth/portability-auth-rememberthemilk/src/main/java/org/datatransferproject/auth/rememberthemilk/RememberTheMilkAuthDataGenerator.java
extensions/auth/portability-auth-smugmug/src/main/java/org/datatransferproject/auth/smugmug/SmugMugAuthDataGenerator.java
extensions/auth/portability-auth-twitter/src/main/java/org/datatransferproject/auth/twitter/TwitterAuthDataGenerator.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/CreateTransferJobAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/GenerateServiceAuthDataAction.java
portability-types-client/src/main/java/org/datatransferproject/types/client/transfer/CreateTransferJob.java
portability-types-client/src/main/java/org/datatransferproject/types/client/transfer/GenerateServiceAuthData.java
portability-types-client/src/test/java/org/datatransferproject/types/client/transfer/CreateTransferJobTest.java

Different frontends may configure callbacks differently, and not necessarily use the "/callback/servicename" convention we had in the API server
Tested photos transfer locally with the demo server

Define callback URLs in the frontend, rather than API

---

libraries/config/build.gradle

This dep is used in the yaml config extension, but not needed in the core config library

Remove unused dep from config library

---

portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/JobAuthorization.java
portability-transfer/src/main/java/org/datatransferproject/transfer/CredsTimeoutException.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerMain.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerModule.java
portability-transfer/src/test/java/org/datatransferproject/transfer/JobPollingServiceTest.java

The timeout can be set in `transfer.yaml` using the property `credTimeoutSeconds`. If not it will default to 5 minutes.
If the worker times out waiting for creds then it will mark the job state as ERROR and the auth state as TIMED_OUT.
Fixes #594

Timeout if waiting too long for creds

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/hooks/DefaultJobHooks.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/hooks/JobHooksExtension.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/hooks/JobHooksLoader.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/hooks/MultiplexJobHooks.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerMain.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerModule.java

As discussed in PR624, converting this interface into an extension that can be loaded using ServiceLoader.

Convert Job Hooks interface into an extension

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/model/BatchMediaItemResponse.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/model/GoogleMediaItem.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/model/Status.java

A small change to alter the return type Google's createPhoto to be correct and add some other small tweaks.
This came up when trying to use photos to hold imported Blogger photos, that code ended up getting thrown away, but these changes should make the photos stack a little easier to use in the future.

Clean up the Google photo handling

---

portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/MonitorLoader.java

Previously, if there were any elements in the list of loaded monitors, line 42 would error out because Java can't cast an Object to a Monitor.  @seehamrun found this page about this bug: https://stackoverflow.com/questions/5374311/convert-arrayliststring-to-string-array

Fixing bug in MonitorLoader

---

extensions/auth/portability-auth-google/src/main/java/org/datatransferproject/auth/google/GoogleOAuthConfig.java

I've tested this and import still works fine for me. This limits the scope and changes the text a user sees on the OAuth screen.

Switch Google Photos import scope to appendonly

---

portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/JobAuthorization.java

I don't recall the entire history of this key, but it is marked deprecated and is only used in one class, GenerateServiceAuthDataAction, which some DTP implementations may not use.
In our case we are seeing a NullPointerException upon deserializing with this field null, so this should fix that:
```
at org.datatransferproject.transfer.JobPoller.pollJob(JobPoller.java:38)
at org.datatransferproject.transfer.Worker.doWork(Worker.java:32)
at org.datatransferproject.transfer.WorkerMain.poll(WorkerMain.java:135)
at org.datatransferproject.transfer.WorkerMain.main(WorkerMain.java:65)
Caused by: java.lang.NullPointerException: Null sessionSecretKey
at org.datatransferproject.spi.cloud.types.AutoValue_JobAuthorization$Builder.setSessionSecretKey(AutoValue_JobAuthorization.java:190)
```

Marking JobAuthorization.sessionSecretKey field nullable

---

portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/PortabilityJob.java

See https://github.com/google/data-transfer-project/pull/661

Don't require sessionSecretKey be present when validating authorization state

---

extensions/data-transfer/portability-data-transfer-spotify/src/main/java/org/datatransferproject/transfer/spotify/playlists/SpotifyPlaylistImporter.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/CreativeWork.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/MediaObject.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/Thing.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/playlists/MusicAlbum.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/playlists/MusicPlaylist.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/playlists/MusicRecording.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideoAlbum.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideoObject.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideosContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/videos/VideosContainerResourceTest.java

This pull request introduces a video datatype in order to prepare for video exporters/importers. Due to the similarity between photos and videos (both MediaItems) the video data type is defined analog to what was already present for photos. Video-importer and -exporter for Google Photos and Facebook will follow in future pull requests.

Video datatype

---

extensions/transport/portability-transport-jettyrest/src/main/java/org/datatransferproject/transport/jettyrest/http/JettyMonitor.java

When a RuntimeException is thrown on the API, JettyMonitor currently logs it as info rather than severe. This changes the mapping to make it severe.
Mapping everything to info makes it much harder to detect issues with the api.

Fix JettyMonitor

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/FlickrTransferExtension.java
extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-flickr/src/test/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/drive/DriveExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/drive/DriveImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosExporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-imgur/src/main/java/org/datatransferproject/datatransfer/imgur/ImgurTransferExtension.java
extensions/data-transfer/portability-data-transfer-imgur/src/main/java/org/datatransferproject/datatransfer/imgur/photos/ImgurPhotosExporter.java
extensions/data-transfer/portability-data-transfer-imgur/src/main/java/org/datatransferproject/datatransfer/imgur/photos/ImgurPhotosImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/MicrosoftTransferExtension.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/calendar/MicrosoftCalendarImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosExporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/integration/MicrosoftCalendarImportTest.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/SmugMugTransferExtension.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosExporter.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosImporter.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/JobStore.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/PersistentPerJobStorage.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/TemporaryPerJobDataStore.java

As per #623 JobStore is really 2 distinct things:
1) a job management interface that is only used by DTP internals
2) a Temp data store for integrations.
This pulls use case 2 into a seperate interface: TemporaryPerJobDataStore.  I am not sold on the name, so any suggestions would be appreciated.
For now JobStore inherits from TemporaryPerJobDataStore, but in future changes that will break.
Also TemporaryPerJobDataStore will should no longer require the JobId for jobs, but that again will come in a latter PR.

Starts to split JobStore into 2 distinct interfaces

---

build.gradle
portability-api-launcher/build.gradle
portability-api-launcher/src/main/java/org/datatransferproject/api/launcher/Version.java
portability-bootstrap-vm/src/main/java/org/datatransferproject/bootstrap/vm/SingleVMMain.java

This PR uses JGit during build to generate a launcher properties file which will be packaged in the API Launcher JAR (or runtime uber jar). The class Version reads the properties file and retrieves the project version and Git hash. The Runtime bootstrap can then access that information.
I updated the SingleVM bootstrapper to output the version and has to the monitor. Other bootstrappers could do the same.

Add support for retrieving the current project version and Git hash

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleDtpInternalMetricRecorder.java
extensions/cloud/portability-cloud-local/src/main/java/org/datatransferproject/cloud/local/LoggingDtpInternalMetricRecorder.java
extensions/cloud/portability-cloud-microsoft/src/main/java/org/datatransferproject/cloud/microsoft/cosmos/AzureDtpInternalMetricRecorder.java
portability-api-launcher/src/main/java/org/datatransferproject/api/launcher/DtpInternalMetricRecorder.java
portability-api/src/main/java/org/datatransferproject/api/ApiServicesModule.java
portability-transfer/src/main/java/org/datatransferproject/transfer/CallableExporter.java
portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerModule.java

Removes importFinished and exportFinished as because we interleave the processing they don't make sense.
This addresses issue #41.

Make the DTP framework call the appropriate metric hooks

---

gradle.properties
portability-types-common/build.gradle

Update AutoValue version and add recently broken out maven package for the Auto value annotations, used in portability-types-common sub project.

update autovalue version

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/StackdriverMonitor.java
extensions/cloud/portability-cloud-local/src/main/java/org/datatransferproject/cloud/local/LocalJobStore.java
extensions/cloud/portability-cloud-microsoft/src/main/java/org/datatransferproject/cloud/microsoft/cosmos/AzureDtpInternalMetricRecorder.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/playlists/DeezerPlaylistExporter.java
extensions/data-transfer/portability-data-transfer-deezer/src/main/java/org/datatransferproject/transfer/deezer/playlists/DeezerPlaylistImporter.java
extensions/data-transfer/portability-data-transfer-spotify/src/main/java/org/datatransferproject/transfer/spotify/playlists/SpotifyPlaylistExporter.java
portability-api-launcher/src/main/java/org/datatransferproject/api/launcher/DelegatingExtensionContext.java
portability-api-launcher/src/main/java/org/datatransferproject/launcher/metrics/LoggingDtpInternalMetricRecorder.java
portability-transfer/src/main/java/org/datatransferproject/transfer/InMemoryIdempotentImportExecutor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerModule.java

Fix calls to Monitor where format was not being applied to strings with obvious String format expressions in them (e.g. %s)

Insert missing uses of String.format

---

portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java

Because most exceptions are caught by the IdepotentExecutor it has been possible for a job to have a bunch of errors, to the point that no photos were transferred, but it could still be marked as complete. This change aims to mark a job as failed if there are any errors left when a copy finishes. (If an import is retried for an item that had previously failed then that error will already be removed on a successful retry)

Mark a job as failed if any errors are returned from the copier

---

Documentation/Integration.md

Previously I moved a lot of the models into common but did not update the documentation https://github.com/google/data-transfer-project/commit/1e31ec8a70b04ac6ceee017e6a51b805d57aa16a

Update docs to reflect where models live

---

extensions/auth/portability-auth-microsoft/src/main/java/org/datatransferproject/auth/microsoft/MicrosoftOAuthConfig.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java

The MicrosoftPhotosImporter was have some issues including an issue with serialisation. The below changes fixed the issues so that a transfer could be run to import photos to Microsoft.

Fix MicrosoftPhotosImporter

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleJobStore.java
extensions/cloud/portability-cloud-local/src/main/java/org/datatransferproject/cloud/local/LocalJobStore.java
extensions/cloud/portability-cloud-microsoft/src/main/java/org/datatransferproject/cloud/microsoft/cosmos/AzureTableStore.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/helper/MockJobStore.java
portability-api/src/main/java/org/datatransferproject/api/action/ActionUtils.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/CreateTransferJobAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/ReserveWorkerAction.java
portability-api/src/main/java/org/datatransferproject/api/action/transfer/StartTransferJobAction.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/JobStore.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/JobStoreWithValidator.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java
portability-transfer/src/test/java/org/datatransferproject/transfer/JobPollingServiceTest.java

This makes sure the JobStore interface only depends on Plain Old Java Objects and does not receive logic dynamically via its arguments. This means we can significantly optimise our JobStore implementation.
Once I removed the concept of passed in validation it meant a mix of specific state transitions and generic updates. To improve validation it seemed like a logical step to make every call on the JobStore a specific state change. This changes the philosophy of the JobStore and is fairly opinionated. I'm happy to discuss/explain this more as it is significant change in that respect (event though actual behaviour should not change).

Refactor JobStore

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java

HttpRequest.execute() throws errors if the response is not 200, so when the refresh token expires, this exception gets thrown: 
```
Caught exception com.google.api.client.http.HttpResponseException: 401 Unauthorized 
at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1072) 
at org.datatransferproject.datatransfer.google.photos.GooglePhotosInterface.makePostRequest(GooglePhotosInterface.java:163) 
at org.datatransferproject.datatransfer.google.photos.GooglePhotosInterface.listMediaItems(GooglePhotosInterface.java:108) 
at org.datatransferproject.datatransfer.google.photos.GooglePhotosExporter.exportPhotos(GooglePhotosExporter.java:201) 
at org.datatransferproject.datatransfer.google.photos.GooglePhotosExporter.export(GooglePhotosExporter.java:129) 
at …
```

Catch HttpResponseExceptions in the GooglePhotosInterface

---

portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/ExponentialBackoffStrategy.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/NoRetryStrategy.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryMapping.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryStrategyLibrary.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryingCallable.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/UniformRetryStrategy.java

I found that it was difficult to tell from the logs which strategy was used for a given error so this logging should make it easier to do so and check that the expected strategies are being used.

Fix bug in UniformRetryStategy and improve logging for retries

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java

I'm guessing that because we specified the nicename, it didn't do its own auto-convert logic. So hopefully removing that will fix it for us.

Remove NiceName specification, revert other encoding change

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java

So that we can pin down why we're still getting 401 errors in the worker after the job reaches 60minutes

Explicitly split up the cases when we refresh the authorization credential

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java

Undoing the changes I thought would fix the special character issue.
This leaves the smugmug integration in a state where it will fail to create albums with special characters in them, but work otherwise

Restore smugmug to functionality of v0.3.5

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/StackdriverMonitor.java
portability-api-launcher/src/main/java/org/datatransferproject/api/launcher/Monitor.java
portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/MultiplexMonitor.java
portability-bootstrap-vm/src/main/java/org/datatransferproject/bootstrap/vm/SingleVMMain.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobCancelWatchingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java

This adds a method to explicitly flush logs which is useful to  do before exiting the process. I have added implementations to the MultiplexMonitor and the Google Cloud StackdriverMonitor.
I have also run Google Java Format 1.7 on the modified files. This is a tradeoff related to https://github.com/google/data-transfer-project/issues/151 and I am happy to discuss this further or reverse the formatting commit.

Add flushLogs method to Monitor

---

extensions/cloud/portability-cloud-local/src/main/java/org/datatransferproject/cloud/local/LocalJobStore.java
extensions/cloud/portability-cloud-local/src/test/java/org/datatransferproject/cloud/local/LocalJobStoreTest.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/JobStore.java
portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java

#742 added the count of imported items, but the interface doesn't allow you to add the items for the job like the rest of the functions. 
@dragosmartac and @wmorland since this changes the interface used.

store count of imported items by job id instead of overall

---

portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java

Incrementing in the string supplier causes multiple increments per iteration if there are multiple monitors.

Fix copy iteration counter

---

portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/auth/AuthData.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/auth/CookiesAndUrlAuthData.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/auth/TokenAuthData.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/auth/TokenSecretAuthData.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/auth/TokensAndUrlAuthData.java

Most subclasses of AuthData have a way to get a token. We currently use introspection to get tokens for revocation but we have to use java reflection. This would allow us to get the token for any AuthData.
It's a bit of a fudge for the CookiesAndUrlAuthData so I'm prepared to make an abstract subclass of AuthData if that is preferred.

Add gettoken to authdata

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/provider/ImportResult.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideosContainerResource.java

By default a DataModel will return a null Counts. This throws a NullPointerException when passed into ImportResult. I make the constructor not throw a NullPointerException and also add a getCounts implementation to VideosContainerResource.

Fix counts nullpointerexception

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java

This can happen if the job was restarted, (since we do all the listing regardless if it the job is a restart). 
This doesnt cause any issues right now and isnt reported as a failure (because it doesnt go through the idempotentexecutor), but would if there were ever photos and albums in the same import call because we would fail before writing out the photos.

If temp data exists in the FlickrImporter, don't try to create it again

---

client-rest/src/environments/environment.ts

idea discussed around here https://github.com/google/data-transfer-project/issues/782#issuecomment-554247636
Whereas the previous default of 'https://localhost:3000' works only in a very narrow set of possible configurations, `document.baseURI` should return whatever base URI at which the page is accessed, even if another hostname or port.

Change default frontend apiBaseUrl to use `document.baseURI` if present

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosInterface.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporterTest.java

This changes GoogleVideosImporter to use IdempotentImportExecutor for the full operation. Also corrects createVideo to map the response to BatchMediaItemResponse. Also google-java-format-1.7.

Fix GoogleVideosImporter

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java

I wanted to handle this issue without marking a transfer as failed. I'm wondering if there should be a category of exceptions/return codes which indicate that there was an issue but that do not result in a transfer being marked as failed? This is a simple fix but I'm happy to handle this edge case in another way if preferred.

Exit GooglePhotosInterface on an empty photo

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java

This reverts commit bbc38c8b18640536cc630c710f06f4a194289784.
Reverting because this actually imposes a couple of other issues on our side and needs to be implemented on the jobstore side of things first. Also this isn't consistent across the other importers that use this sort of temp data

 Revert "If temp data exists in the FlickrImporter, don't try to create it again (#790)"

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java

We were using the hashcode before which caused the IDs to be different when jobs were restarted. Both the albumid and photoid are used because we need a way to store photos in multiple albums, this is already being done in the flickr and google importers: 
https://github.com/google/data-transfer-project/blob/master/extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java#L102
https://github.com/google/data-transfer-project/blob/master/extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java#L154

Use album id and photo id as the idempotent ids in MicrosoftPhotosImporter

---

portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/events/EventCode.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobCancelWatchingService.java

Add an EventCode and increase the log level for when a job is terminated because it has been canceled.

Improve job cancellation logging

---

client-rest/src/environments/environment.ts

Fixes #800 
With this change, API calls will now be formed by a base URL that is cleaned up to remove any trailing slashes.

Fix Demo Server environment.apiBaseUrl

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosImporter.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotoAlbum.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotoModel.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotosContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/photos/PhotosContainerResourceTest.java

Adds a "transmogrification" function to the PhotosContainerResource that allows for coercion to meet a services' particular restrictions (currently album size and existence of loose photos; eventually this could include filetype coercion, size limitation, etc.)
As-implemented, just gets called from the SmugmugPhotosImporter, but in the long run could be generalized to read from some sort of per-service config.

Add photo model coercion logic to generally account for loose photos and album size

---

.travis.yml

Not sure why this started failing but this answer and linked documentation suggests this could solve it https://travis-ci.community/t/the-following-packages-cannot-be-authenticated-google-chrome-stable/6866/6

Add chrome stable to travis.yml

---

extensions/data-transfer/portability-data-transfer-microsoft/build.gradle
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/DataChunk.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/DataChunkTest.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporterTest.java

According to this, for files larger than 4MB, it is required that we use createUploadSession of the OneDrive API.
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#create-an-upload-session
This code completes that requirement, and now we can upload files that are larger than 4MB to OneDrive 😲

Make MicrosoftPhotosImporter use upload sessions

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/PhotoResult.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/VideoResult.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/PhotoResultSerializationTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/VideoResultSerializationTest.java

Because the Result classes were inner classes serialization broke. It was trying to serialize the outer class which was not possible. This adds unit tests to verify.

Fix serialization bug

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/CopyException.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/CopyExceptionWithFailureReason.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/DestinationMemoryFullException.java
portability-transfer/src/main/java/org/datatransferproject/transfer/InMemoryDataCopier.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java

So exceptions can store the failure reason on the exception and we have no MemoryFull specific logic.

Create an abstract CopyExceptionWithFailureReason

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/common/GoogleCredentialFactory.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/FailureReasons.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/InvalidTokenException.java

Two main advantages to this:
1. We don't keep retrying if a token is invalid (this change does not touch the refresh logic though)
2. We store a specific failure reason
This definitely needs review from Google folks as it affects the GooglePhotosExporter.

Create an InvalidTokenException and throw from GoogleCredentialFactory

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java

This should prevent the consistent timeout errors we're seeing when listing some of the albums:
ex:
```
Error processing jobId: 374efb2e-10c6-4ca8-9bdb-3f535939819d
org.datatransferproject.transfer.CopyException: Job 374efb2e-10c6-4ca8-9bdb-3f535939819d: Error happened during export
at org.datatransferproject.transfer.PortabilityInMemoryDataCopier.copyHelper(PortabilityInMemoryDataCopier.java:137)
at org.datatransferproject.transfer.PortabilityInMemoryDataCopier.copy(PortabilityInMemoryDataCopier.java:93)
at org.datatransferproject.transfer.JobProcessor.processJob(JobProcessor.java:123)
at org.datatransferproject.transfer.Worker.doWork(Worker.java:39)
at org.datatransferproject.transfer.WorkerMain.poll(WorkerMain.java:138)
at org.datatransferproject.transfer.WorkerMain.main(WorkerMain.java …
```

Update the GooglePhotosInterface read timeout to 2 minutes instead of the default two seconds.

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java

This ideally should be done in a transmogrification config, but there isnt one hooked up to flickr yet and the existing config doesnt handle empty titles.
We can fix this later on

Allow flickr to import untitled albums

---

extensions/data-transfer/portability-data-transfer-google/build.gradle

This includes the change to configure the http client through the Java system properties.

Bump google-photos-library-client to 1.5.0

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java

Can be set via the setting 'googleWritesPerSecond' or will default to 1/second

Rate limit writes to Google Photos to avoid hitting the per user rate limits.

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/model/SmugMugImageUploadResponse.java

SmugMug's API returns 200 when an image fails to upload, so the code was failing to catch any failures, resulting in missing data. Now we check for failures by looking at the 'stat' field of the API response.

check for image upload failure

---

libraries/auth/src/main/java/org/datatransferproject/auth/OAuth2DataGenerator.java

Summary:
Currently, demo server web UI does not redirect to Auth URL to service
providers. Instead it would revert back to localhost:3000 to start
everything over again. This is due to the backend server does not
construct the auth URL correctly.
This commit is to fix that.
Test Plan: Demo UI should proceed to auth url for user to authorize as expected.

Fix wrong authurl when doing oauth on devserver

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/FailureReasons.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/PermissionDeniedException.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/UploadErrorException.java

Summary:
Currently, when user import photos to google photos, the user needs to
select the google account with access to photos.
Otherwise, Google API would reply with a 403 error which cause a Java
IOException.
This commit is to capture this 403 error in a new exception class based
on CopyExceptionWithFailureReason. So it would allow displaying better
error message to the front end users.
Test Plan:
Import photos to a google account with no access to photos. Worker
should throw a PermissionDeniedException rather than an IOException

Add new exception to capture user permission denial

---

portability-transfer/src/main/java/org/datatransferproject/transfer/JobCancelWatchingService.java

This reflects the fact that the application did not crash and instead stopped as requested by the user.

Switch the stopped job exit code to 0

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java

Summary:
Currently google photo importer create a new google photo interface
every time it sends a http request.
If the original access token is expired, the new access token acquired
from refresh token would not be persisted across http request.
This commit is to fix the inefficiency here that we don't create a new
google photo interface every time we send a new request.
Test Plan:
Send request after access token expires then the refresh action should
only happen once for the next few requests.

Fix token refresh issue for google photo importer

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleDtpInternalMetricRecorder.java
extensions/cloud/portability-cloud-microsoft/src/main/java/org/datatransferproject/cloud/microsoft/cosmos/AzureDtpInternalMetricRecorder.java
portability-api-launcher/src/main/java/org/datatransferproject/api/launcher/DtpInternalMetricRecorder.java
portability-api-launcher/src/main/java/org/datatransferproject/launcher/metrics/LoggingDtpInternalMetricRecorder.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobCancelWatchingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobMetadata.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java

Summary:
Currently when a job is started and then cancelled by user, dtp worker
would only print the startedJob metrics line in the log. This makes the
log line incomplete and confuses engineers with unfinished job.
The commit here is to add the finishedJob metrics in job cancellation.
Test Plan: Cancel a job and see the new log line appearing there.

Add finishedJob metric when job is cancelled

---

extensions/auth/portability-auth-google/src/main/java/org/datatransferproject/auth/google/GoogleOAuthConfig.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java

Summary:
Currently once google auth token expires after 1 hour, all video imports
would be rejected by Google due to invalid token.
This commit is to ask the video importer always refresh token before it
sends the first http request. So the right expiry time would be filled in for the job. 
Test Plan: Test by using expired token to transfer video and the refresh logic would kick in.

Fix token issue when importing video to google

---

portability-transfer/src/main/java/org/datatransferproject/transfer/PortabilityInMemoryDataCopier.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryingCallable.java

Summary:
We would like to better keep track of retrying activities across
different data types and services.
Adding extra logging to record service and data type info when retrying.
Test Plan: Do a transfer which requires retry and check the log line
example log line -
```
DEBUG 2020-06-09T15:27:18.422 Attempt 1 failed, using retry strategy: ExponentialBackoffStrategy{maxAttempts=5, initialIntervalMillis=1000, multiplier=1.5}, service: Google, dataType: PHOTOS
DEBUG 2020-06-09T15:27:18.424 Strategy has 999 remainingIntervalMillis after 1 elapsedMillis
DEBUG 2020-06-09T15:27:19.425 Make 2 attempt of retry to service Google on data type PHOTOS
```

Add per service per data type logging to RetryingCallable

---

portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java

Summary:
When an exception is thrown during finding job or starting job, it would
terminate the whole worker because it will be uncaught.
This commit is to catch those exceptions and make best effort to mark
the job failed when these happen.
Test Plan:
Throw out exception in these cases and see if the error is gracefully
handled.
Log lines after test:
> DEBUG 2020-06-17T13:23:11.786 Begin processing jobId: 8d2627e3-748e-44e5-94b6-b1692648367d
> EventCode: WORKER_JOB_STARTED
> SEVERE 2020-06-17T13:23:11.787 Error processing jobId: 8d2627e3-748e-44e5-94b6-b1692648367d
> java.lang.RuntimeException
> 	at org.datatransferproject.spi.cloud.storage.JobStoreWithValidator.markJobAsStarted(JobStoreWithValidator.java:72)
> 	at org.datatransferproject.transfer.JobProcessor.markJobStarted(JobProcessor. …

Catch uncaught exceptions when job starts

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/IdempotentImportExecutor.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/InMemoryIdempotentImportExecutor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java

Summary:
Currently in CallableImporter, the code would call getErrors on
idempotentExecutor to determine if there was any error when importing.
However, this getErrors would contain ALL errors happened in the
previous import actions, not errors only happened for the current
import. This would mean one import error in the early stage would cause
retry for all subsequent import actions.
This commit is to add new methods to track only recent errors on
executor and only throw out exceptions when those recent errors are
created.
Test Plan:
Raise one IOException when importing and check if it would impact the
subseqent import retries.

Fix wrong importer retry due to getErrors on executor

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java

Summary:
Previously we got a null pointer exception when importing a single photo into Google Photos.  This commit adds null checks and instead throws an IOException, which can be used by our workers to retry a photo import.
Test Plan: Ran a test transfer in Docker. Add a test to confirm that an IOException is raised, not a NullPointerException.

Handle NullPointerException when unwrapping Google Photos response

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java

We were sometimes seeing errors that looked like this 
```
body: {
"error": {
"code": "itemNotFound",
"message": "Item does not exist",
"innerError": {
"request-id": "df29ffc5-7dc6-4f2f-afd8-f03bd7f9bd8a",
"date": "2020-05-18T08:10:12"
}
}
}
request url: https://graph.microsoft.com/v1.0/me/drive/root:/Pictures/REDACTED.jpg:/createUploadSession?@microsoft.graph.conflictBehavior=rename
bearer token: REDACTED 
```
From looking at the microsoft docs, the 404 indicates that the resource doesn't exist, which leads us to believe that either the user doesnt have onedrive enabled, or the Pictures folder on the account doesn't exist. It is possible to delete the Pictures root folder from your onedrive account, but it looks like the folder gets recreated when we create the album folders and upload …

Update albumlessphoto url for microsoft to be the /special/photos URL

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosExporter.java

This gets triggered after we are done exporting all named albums by sending in an album with an empty title. 
Note: it is impossible for an album to have an empty title in Flickr, this is enforced in their UI when you create an album and in the API when you create an album, so we'll never have a collision here. And since this doesn't actually add an `AlbumContainerResource` there is no issue with it appearing in any importer as an album either (it will just trigger the subresources to be processed).
Fixes #906

Export albumless photos in the flickr exporter

---

portability-api/src/main/java/org/datatransferproject/api/action/transfer/CreateTransferJobAction.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/PortabilityJob.java
portability-spi-cloud/src/test/java/org/datatransferproject/spi/cloud/types/PortabilityJobTest.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java

Previously we were expecting that the builder be able to pull out the the ExportInformation from the map, however the cloud extension thats used writes this out as a json string
Interested in thoughts here, we already deserialize objects in the Processor (ex: the AuthData pair). The other thing we can do is deserialize in the Cloud extension, but we dont have a good convention for what is and isnt deserialized (or decrypted) there.

Read ExportInformation as a string and deserialize it in the JobProcessor

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosInterface.java

This is a quick first pass at enabling exporting specific resources in these exporters. 
Previously they only accepted IdOnlyContainerResources in the export information. This assumes that if the ExportInformation contains a PhotosContainerResource that the export process should start there instead of listing out all the user media items

Enable exporting of specific resources in the GooglePhotosExporter and FlickrPhotosExporter

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/ContainerResource.java

I noticed that VideoContainerResource was not a subtype of ContainerResource.
This diff corrects the ContainerResource file to add the other subtypes of Container resource, the only exception being BlobbyDataContainerResource - this is because it resides in another module and doing so would introduce a cyclic build dependency. (https://github.com/google/data-transfer-project/issues/916 already flags this).

Update subtypes of ContainerResource

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/calendar/CalendarAttendeeModel.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/calendar/CalendarContainerResource.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/calendar/CalendarEventModel.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/calendar/CalendarModel.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/mail/MailContainerModel.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/mail/MailContainerResource.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/mail/MailMessageModel.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/tasks/TaskContainerResource.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/tasks/TaskListModel.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/tasks/TaskModel.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideosContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/calendar/CalendarContainerResourceTest.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/mail/MailContainerResourceTest.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/photos/PhotosContainerResourceTest.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/tasks/TaskContainerResourceTest.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/videos/VideosContainerResourceTest.java

Currently serialisation and deserialisation tests checking object equality fail because the VideosContainerResource does not override equals() unlike PhotosContainerResource. This PR updates the VideoContainerResource and Task and Calendar container resources to override equals().
Updated tests so they check object equality between the deserialised object and the original data.

Override equality for container resources

---

portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java

Summary:
Job being cancelled is a perfectly valid action. When that happens, java
worker should not log a severe log line.
Change the log line to info
Test Plan: Did a transfer on cancelled job and checked the log line.

Change job cancellation polling logging to info

---

extensions/data-transfer/portability-data-transfer-facebook/src/main/java/org/datatransferproject/transfer/facebook/photos/FacebookPhotosExporter.java
extensions/data-transfer/portability-data-transfer-facebook/src/test/java/org/datatransferproject/transfer/facebook/photos/FacebookPhotosExporterTest.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotoModel.java

We want to be able to pass a time property straight through to adapters who can then use it for media sorting or setting properties. Ideally we will use this with the Google Photos API if https://issuetracker.google.com/issues/133782941 is resolved.

Add uploadedTime property to PhotoModel

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporterTest.java

We see a small number of transfers fail because a video has been provided by the API but is then deleted.

Handle FileNotFound exception when a video has been deleted

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/MicrosoftTransmogrificationConfig.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporterTest.java

We were getting errors for certain albums like this: 
```
org.datatransferproject.types.transfer.retry.RetryException: java.io.IOException: Problem with importer, forcing a retry, 2 errors, first one: ErrorDetail{id=ANUH2qoydPFKocl1xJ7RJ56lLhVrLm4j-Q1jl3DLkhMcwjvwuXHzB1gzMxONyACx8ljAvbbBfSjw, title=REDACTED, exception=java.io.IOException: Got error code: 400 message: Bad Request body: {
"error": {
"code": "invalidRequest",
"message": "Path (REDACTED) contains invalid trailing character.",
"innerError": {
"code": "nameContainsInvalidCharacters",
"date": "2020-08-04T15:16:36",
"request-id": "a2f1831e-e40f-4103-acee-67b858193482"
}
}
}
```
I've removed the album title, but for all the cases we've seen this was when the title ended in a period. I cant find any official documentation on this …

Add period `.` to list of forbidden album name characters

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporterTest.java
portability-test-utilities/src/main/java/org/datatransferproject/test/types/FakeIdempotentImportExecutor.java

We were comparing strings using == which was leading to this error not properly being categorized 
When writing the tests, this also uncovered that the fake idempotent executor was wrapping all exceptions as IOExceptions, causing failures to not propagate in tests. Ive fixed that and updated the test

Properly categorize and throw PermissionDeniedException in MicrosoftPhotosImporter

---

extensions/data-transfer/portability-data-transfer-facebook/src/main/java/org/datatransferproject/transfer/facebook/videos/FacebookVideosExporter.java
extensions/data-transfer/portability-data-transfer-facebook/src/main/java/org/datatransferproject/transfer/facebook/videos/RestFbFacebookVideos.java
extensions/data-transfer/portability-data-transfer-facebook/src/test/java/org/datatransferproject/transfer/facebook/videos/FacebookVideosExporterTest.java

This was previously returning blank descriptions as the string is now available through the API as the field 'description'. See https://developers.facebook.com/docs/graph-api/reference/v7.0/video/#fields for reference

Fix an issue where we fetched an inaccurate field for the description

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporterTest.java

This is a change to truncate descriptions when importing into Google Videos to ensure that videos with descriptions > 1000 chars are not rejected.  A similar piece of code is already in place for photos..

Perform truncation of videos descriptions > 1000 chars to reduce failure rates for Google Video imports

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/ContainerResource.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/DateRangeContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/DateRangeContainerResourceTest.java

We are adding this container resource so that we can pass a Date Range between which we want to transfer the data. Basically we will only query and transfer the data that lies between the start and end date passed in the date range container resource.
The start and end date passed will be unix timestamps, hence we thought it would be best to pass them as integers.
The container resource will be passed initially along with job creation. Though currently we are creating this as a stand-alone filtering option, we might allow the users to couple this filter with additional filters like Album selection (via Photos Container Resource).
We will be changing the existing exporters to support this new container resource.

Adding DateRangeContainerResource for filter by date usecase

---

portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java

Summary:
Currently CallableImporter throws out an IOException if
IdempotentImportExecutor recorded errors. This IOExcpetion would be
printed to severe logging if the subsequent retry failed. However, the
content of the exception contains first error and error counts. And
these are already duplicatedly logged in IdempotentImportExecutor. This
cause logs to spam and hard to categorize errors.
This commit is to simplify that by removing the spamming part of the
log.
Test Plan: Ran and checked the log line

Reduce duplicate logging in CallableImporter

---

portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java

Summary:
We removed the error details from the logline in previous commit.
However, this log line is essential to our retry logic since we are
doing string matching to determine how worker is going to do the retry.
This commit is to add the first error back to the log line.
Test Plan: Build and verify the logline

Readd log lines for first retryable error

---

portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/social/SocialActivityAttachmentType.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/social/SocialActivityContainerResourceTest.java

Adding new enum value - VIDEO to SocialActivityAttachmentType. This will allow working with Social activity entities which contains videos.

Add VIDEO as acceptable social attachment type

---

portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java

Summary:
Currently we are logging out both id and title of error details to
Retryable Import Exception. However, this makes the log line hard to be
categorized.
Since we are only logging the first error and we log error for
individual transfer item in the end, we can remove id and title from
here.
This commit is to do that.
Test Plan: build and check log line

Only add exception of error details to retryable exception

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/social/SocialActivityContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/social/SocialActivityContainerResourceTest.java

Summary: Added getCounts implementation which returns an immutable map containing count for the activities.
Test Plan: 1. Added Test Case for the getCounts methods. 
2. ./gradlew build test - Successful
Reviewers: @wmorland 
Subscribers:
Tasks: T83723263
Tags:
Blame Revision:
Differential Revision: https://phabricator.intern.facebook.com/D26174322

Added getCounts implementation to SocialActivityContainerResource

---

extensions/data-transfer/portability-data-transfer-backblaze/build.gradle
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/BackblazeTransferExtension.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClient.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClientFactory.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/exception/BackblazeCredentialsException.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/package-info.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporter.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporter.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/resources/META-INF/services/org.datatransferproject.spi.transfer.extension.TransferExtension
settings.gradle

Facebook and Backblaze teams worked together last year to enable Photos and Videos transfers from Facebook to Backblaze. And it was [launched in October 2020](https://about.fb.com/news/2020/09/expanding-photo-and-video-transfer-tool-to-dropbox-and-koofr/).
This PR adds the Backblaze transfer extension to the project and currently includes a photos importer and a videos importer.
The code is tested, and is deployed in production for all Facebook users at https://www.facebook.com/dtp

Backblaze import adapters for photos and videos

---

portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/events/EventCode.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobCancelWatchingService.java

Changes done:
Updating JobWatching service to check the job state as Preempted or errored.
This is one of the edge case which is to check whether the current job is errored or preempted, and stop the worker job all together.
Earlier, the JobWatching service was exiting the system in case job is cancelled.

Updating Job Watcher service

---

libraries/security/src/main/java/org/datatransferproject/security/EncrypterImpl.java

EncrypterImpl is encrypting a salt to avoid needing to store the IV, but currently throws it away instead of returning it with the ciphertext. DecrypterImpl then throws away the first decrypted block, intending to throw away the salt, but instead it's part of the plaintext.
This includes the first encrypted block in the return as intended.
This was discovered while testing #961 but the fix is separate.

Include encrypted salt as intended

---

extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/KoofrTransferExtension.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/photos/KoofrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/photos/KoofrPhotosImporterTest.java
portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/types/PortabilityJob.java
portability-spi-cloud/src/test/java/org/datatransferproject/spi/cloud/types/PortabilityJobTest.java

When a user creates a transfer job we do not consider their timezone on the backend worker and instead all dates simply match to the timezone of the server. To fix this we added a field to the job which exporters and importers can use to render dates in the user's time zone.
- Added the user timezone field to PortabilityJob. 
- Used the timezone field in KoofrPhotosImporter. This means that the dates in the titles get formatted to match the user's timezone preference (if the timezone has not been set we default to the system timezone).

Add a user timezone field to PortabilityJob

---

portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/TemporaryPerJobDataStore.java

Fixes #968 
Files.createTempFile does not set world readable permissions https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createTempFile(java.nio.file.Path,%20java.lang.String,%20java.lang.String,%20java.nio.file.attribute.FileAttribute...)

Switch to using Files.createTempFile

---

distributions/demo-server/build.gradle

This re-orders the Dockerfile steps for the `demo-server` distribution to run the less-frequently-changing commands first. The DTP-specific files (the demo client and the API/Transfer jar) are copied into the image last. This allows Docker to use the image cache more efficiently and speeds up rebuilding the Docker image when only the DTP code has changed.

Update demo-server Dockerfile

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/hooks/JobHooksLoader.java

When trying to implement a `JobHooksExtension` the following error is thrown:
```
java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [Lorg.datatransferproject.spi.transfer.hooks.JobHooks;
```
This fixes the casting error by using the typed form of `toArray()`.

Fix casting error for JobHooks array

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosImporter.java
extensions/data-transfer/portability-data-transfer-smugmug/src/test/java/org/datatransfer/smugmug/photos/SmugMugPhotosImporterTest.java

During test imports we would see this error caused by the album name being null. This handles the empty photo album name the same way that the Flickr Importer does, at the Importer level instead of at the interface level. This would allow us then to use some of the language support that was added in #972 more easily 
```
RetryingCallable caught an exception
java.io.IOException: Problem with importer, forcing a retry, first error: java.lang.NullPointerException
at org.datatransferproject.transfer.smugmug.photos.SmugMugInterface.cleanName(SmugMugInterface.java:251)
at org.datatransferproject.transfer.smugmug.photos.SmugMugInterface.createAlbum(SmugMugInterface.java:94)
at org.datatransferproject.transfer.smugmug.photos.SmugMugPhotosImporter.importSingleAlbum(SmugMugPhotosImporter.java:109) …
```

Handle empty album names in the Smugmug Importer.

---

extensions/auth/portability-auth-flickr/src/main/java/org/datatransferproject/auth/flickr/FlickrOAuthConfig.java
extensions/auth/portability-auth-smugmug/src/main/java/org/datatransferproject/auth/smugmug/SmugMugOAuthConfig.java
extensions/auth/portability-auth-twitter/src/main/java/org/datatransferproject/auth/twitter/TwitterOAuthConfig.java
libraries/auth/src/main/java/org/datatransferproject/auth/OAuth1Config.java
libraries/auth/src/main/java/org/datatransferproject/auth/OAuth1DataGenerator.java
libraries/auth/src/main/java/org/datatransferproject/auth/OAuth1ServiceExtension.java

Updates OAuth1Config and the implementing classes to support additional parameters.
The OAuth1 spec allows parameters on the token request and authorization URLs. The old configs only supported a single "scope" parameter. This allows multiple parameters, based on the combination or URL, data type, and mode.
Adds an additional parameter for SmugMug to allow reading and writing of private albums as necessary.

Update OAuth1Config for additional parameters

---

extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosExporter.java

PR #989 updated the SmugMug OAuth tokens to include "Full" permissions, allowing the SmugMug exporter and importer to operate on non-public resources (including private and passworded albums).
This removes the restriction that disallowed exporting private albums. Export URLs are already being signed with OAuth (despite the comment), and these will now work.

Allow exporting from SmugMug private albums

---

extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-flickr/src/test/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosExporterTest.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosImporter.java
extensions/data-transfer/portability-data-transfer-smugmug/src/test/java/org/datatransfer/smugmug/photos/SmugMugPhotosImporterTest.java

This also fixes a bug that was introduced in #981 where the copy of prefix gets added twice for the title of the album here: https://github.com/google/data-transfer-project/blob/9614d543897a5b6235344476922457d57e666914/extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugInterface.java#L98

Remove copy of prefix for all photos importers

---

extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporter.java
extensions/data-transfer/portability-data-transfer-facebook/src/main/java/org/datatransferproject/transfer/facebook/videos/FacebookVideosExporter.java
extensions/data-transfer/portability-data-transfer-facebook/src/main/java/org/datatransferproject/transfer/facebook/videos/FacebookVideosImporter.java
extensions/data-transfer/portability-data-transfer-facebook/src/test/java/org/datatransferproject/transfer/facebook/videos/FacebookVideosExporterTest.java
extensions/data-transfer/portability-data-transfer-facebook/src/test/java/org/datatransferproject/transfer/facebook/videos/FacebookVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosExporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/common/KoofrMediaExport.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosExporter.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosImporter.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosExporterTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosImporterTest.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideoModel.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideosContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/videos/VideosContainerResourceTest.java

Ex, we have `PhotosModel` , `TaskModel`, `SocialActivityModel` and several others.

Rename `VideoObject` to `VideoModel` to follow the naming convention we use for most of the other data models

---

portability-transfer/src/main/java/org/datatransferproject/transfer/copier/PortabilityAbstractInMemoryDataCopier.java

Currently when copy iteration fails in the importer and when the exception thrown is not assignable from CopyExceptionWithFailureReason we mark transfers as successful. Throwing generic copy exception will make sure that transfers are marked as failed.

Throw generic copy exceptions to mark transfers as failed when copy iteration fails in importer

---

gradle.properties

see e.g. https://github.com/vorburger/Log4j_CVE-2021-44228/

bump log4j from 2.11.0 to 2.15.0 in gradle.properties

---

gradle.properties

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105

 Update log4j to 2.17 to address CVE-2021-45105.

---

build.gradle

Added gradle tasks for bumping project versions. This can be an initial step to avoid changing versions manually in the settings file. Ideally, we should manage project version during release.

Add gradle tasks for bumping version

---

extensions/cloud/portability-cloud-google/src/main/java/org/datatransferproject/cloud/google/GoogleCloudIdempotentImportExecutorExtension.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/IdempotentImportExecutorExtension.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/IdempotentImportExecutorLoader.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerMain.java

We want to keep track of a single item transfer state for giving users more visibility of what photo/video/etc. were transferred successfully. One possible solution could be adding transfer item state management logic to the IdempotentImportExecutor. In this case, we will need to add ExtensionContext dependency to the IdempotentImportExecutor, so we can use JobStore to update item state.

Adding extension context to idempotent executor

---

extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporter.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-daybook/src/main/java/org/datatransferproject/transfer/daybook/photos/DaybookPhotosImporter.java
extensions/data-transfer/portability-data-transfer-flickr/src/main/java/org/datatransferproject/datatransfer/flickr/photos/FlickrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/photos/KoofrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java
extensions/data-transfer/portability-data-transfer-smugmug/src/main/java/org/datatransferproject/transfer/smugmug/photos/SmugMugPhotosImporter.java
extensions/data-transfer/portability-data-transfer-twitter/src/main/java/org/datatransferproject/transfer/twitter/TwitterPhotosImporter.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/IdempotentImportExecutorHelper.java

We want to update the item (photo in this case) transfer state that we can report to the users in the IdempotentImportExecutor. It's easier to accomplish in case we have a unique way of calculating idempotentId among photo import services.

Unifying photo import idempotent id calculation

---

extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/BackblazeTransferExtension.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/common/BackblazeDataTransferClientFactory.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporter.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporter.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporterTest.java

this prevents the race condition where we need to use a different set of auth data for a different job but use the old client factory

Switch BackblazeTransferClientFactory from using 1 single client for every job to keeping a map of clients based on JobId

---

portability-spi-cloud/src/main/java/org/datatransferproject/spi/cloud/storage/JobStore.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobCancelWatchingService.java

This change adds capability to add hooks for Job workers to do some clean up at their end when Jobs are intentionally/abruptly cancelled or fail. 
The new addition will allow JobStore implementations to provide their choice of handling for workers when Jobs are abandoned.

Add hook for Job Cancellations

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/media/MediaContainerResource.java

Proof of fix is in my `msoft-add-media-importer` branch tests passing.
There's no unit tests for this class, so I'm punting on that issue for
now.

fix #1052 constructors' ternary has copy-pasta bug

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/media/MediaContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/media/MediaContainerResourceTest.java

see #1058 description
here's a more accurate diff of what I've done:
```sh
$ cd portability-types-common/src/test/java/org/datatransferproject/types/common/models
$ mkdir media
$ cp photos/PhotosContainerResourceTest.java media/MediaContainerResourceTest.java
$ diff -u photos/PhotosContainerResourceTest.java <(git show ddd111b0d008d233c147efe:./media/MediaContainerResourceTest.java )
```
**tl;dr** of this diff (and PR) IMO: I forked test code (`{Photos,Media}ContainerResourceTest`), deleted transmogrification stuff that we're not doing in the new MediaContainerResource (per issue #1000) and wrote TODO(#1060) atop the file.
```diff
--- photos/PhotosContainerResourceTest.java	2022-02-09 12:26:07.209995906 -0600
+++ /dev/fd/63	2022-04-15 20:10:59.645780170 -0500
@@ -1,4 +1,4 @@
-package …
```

fixes #1058: add MediaContainerResourceTest & more

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/media/MediaAlbum.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/media/MediaContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/media/MediaContainerResourceTest.java

[this is the sort of not-blatantly-forking][techdebt-dedupe-media-vertical] strategy that _this_ PR is meant to enable with little-to-no throwaway code.
[techdebt-dedupe-media-vertical]: https://github.com/jzacsh/data-transfer-project/compare/msoft-add-media-importer...jzacsh:techdebt-dedupe-media-vertical
---
~Note: I don't _think_ we've setup [any PR-Dependency tooling](https://github.com/github/feedback/discussions/4477#discussioncomment-1039627) for this github project, right? (so beware: don't merge this until 1059 is merged)~
~Depends on #1059~ resolved.

noop(feature) new static APIs on Media classes

---

build.gradle
distributions/api-default/build.gradle
distributions/demo-google-deployment/api/build.gradle
distributions/demo-google-deployment/transfer/build.gradle
distributions/demo-server/build.gradle
distributions/transfer-default/build.gradle

[JCenter has been deprecated](https://blog.gradle.org/jcenter-shutdown) for some time.
>Based on the current timeline, builds that use JCenter will be able to resolve dependencies until February 1, 2022 without changes. After that date, there are no guarantees that you will be able to build your software if you continue to use JCenter.

Use Maven Central Repository instead of deprecated JCenter

---

extensions/data-transfer/portability-data-transfer-google/build.gradle
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java

Pair is not supported by Guava and we were using an older gdata pair, switch to using supported apache pair instead

Remove usage of old Pair in GooglePhotosImporter

---

portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/ExponentialBackoffStrategy.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/UniformRetryStrategy.java

We are adding a parameter called 'identifier' at Facebook to distinguish the Retry Strategy actually used, using our logs. This is a backward compatible change, if the 'identifier' field is not passed, it is defaulted to 'null'.

Add support for Retry Strategy Identifier

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotoAlbum.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/photos/PhotosContainerResource.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/photos/PhotoAlbumTest.java

Changes:
* `!equals` instead of `!=` when comparing string album IDs;
* simpler `PhotoAlbum::split`;
* basic tests for `PhotoAlbum`;
* formatting of every file I touched.
Looks like we use this `!=` comparison to find the album for the given group of photos. It was introduced in https://github.com/google/data-transfer-project/pull/805. I *suspect* the comparison bug didn't really show itself because the album ids for photos are probably reused everywhere (therefore have the same pointer).
I'll make the container resource easier to understand in the following PRs.

Fix equals bug in photos resource

---

gradle.properties

Following releases [`0.3.65`](https://github.com/google/data-transfer-project/releases/tag/v0.3.65) and [`0.3.66`](https://github.com/google/data-transfer-project/releases/tag/v0.3.66).

Bump version to 0.3.67

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java

Following #1079 migrating Google photo and video importers to the new API. The new API supports size reporting.

Migrate Google importers to the new executor API

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/ItemImportResult.java
portability-spi-transfer/src/test/java/org/datatransferproject/spi/transfer/idempotentexecutor/ItemImportResultTest.java

1. Every error must have an exception. If a client does not have one it has to create one.
2. Added some unit tests.
Test plan: `ItemImportResultTest`.

Make exception mandatory on error

---

extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporter.java
extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporter.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporterTest.java

Following https://github.com/google/data-transfer-project/pull/1079 migrating Blackblaze photo and video importers to the new API. The new API supports size reporting.

Migrate Blackblaze importers to new executor API

---

distributions/demo-server/build.gradle

It's a partial reversal of https://github.com/google/data-transfer-project/pull/1075. `dockerize` does not work without `jcenter`—it can't find `docker-java-shaded`.
Try running `./gradlew :distributions:demo-server:dockerize` without the changes. It fails with
```
* What went wrong:
Execution failed for task ':distributions:demo-server:dockerize'.
> Could not resolve all files for configuration ':distributions:demo-server:dockerJava'.
> Could not find com.aries:docker-java-shaded:3.0.14.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.pom
- https://repo.maven.apache.org/maven2/com/aries/docker-java-shaded/3.0.14/docker-java-shaded-3.0.14.jar
Required by:
project :distributions:demo-server
``` …

Fix dockerize

---

Documentation/Publishing.md
Documentation/RunningLocally.md

1. More detailed release instructions.
2. Fixed path to `env.secrets`.
3. More detailed dockerize instructions.
4. Expanded note on versioning and dedicated a section number 0 to it.

Fix and improve docs

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/mediaModels/GoogleAlbum.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java

The [API reference](https://developers.google.com/photos/library/reference/rest/v1/albums#Album) defines `isWriteable` property, not `isWritable`.

fix typo introduced in #1109

---

build.gradle

`hasProperty` uses a local context, while `project.hasProperty` references the global value

[bugfix] fix the way we get ossrh credentials during gradle build

---

build.gradle
distributions/demo-google-deployment/api/build.gradle
distributions/demo-google-deployment/transfer/build.gradle
distributions/demo-server/build.gradle

closes #1115 
I had to update the plugin version—the previous one didn't work without jcenter. The new version is backward-incompatible with the previous one, so I updated some of the calls.
You might be wondering why I decided to add this plugin to `buildscript` instead of using beautiful `plugin { id .. }` syntax. The latter one didn't work for some reason and I just went with the option that did work. 
--- 
I tested by following [Running Locally](https://github.com/google/data-transfer-project/blob/master/Documentation/RunningLocally.md) instructions for **demo-server only (I did not check other images)**:
1. Build an image: `./gradlew :distributions:demo-server:dockerize`.
2. Run: `docker run --rm -p 3000:443 -p 5005:5005 -p 8080:8080 --env-file env.secrets --name dtp-demo …

Update docker plugin and remove JCenter dependency

---

extensions/data-transfer/portability-data-transfer-backblaze/src/main/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporter.java

`importSingleVideo` is called inside 'swallow IO exceptions' method call. `FileNotFoundException` is an `IOException` meaning we want—and indeed do—to swallow it. I believe this qualifies as an 'info' message, not a severe one.

Log FileNotFound as INFO instead of SEVERE

---

distributions/demo-server/src/config/demo/supervisord.conf

I broke it when migrating to Java 11 in https://github.com/google/data-transfer-project/pull/1114.

Fix Java debugging of a running docker container

---

build.gradle
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/photos/BackblazePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-daybook/src/test/java/org/datatransferproject/transfer/daybook/photos/DaybookPhotosImporterTest.java
portability-api/src/test/java/org/datatransferproject/api/auth/PortabilityAuthServiceExtensionRegistryTest.java

* Added Jupiter engine dependency
* Added Unit test logging indicating test run state.
* Fixes the issue where some Junit5 tests might not be picked up & tested.
* Modified Junit5 @Test to Junit4 annotations on files that require other migration to be done before upgrading, which might fail if updated now. (eg) @Rule is not supported in Junit5 @Test classes

Add junit5 jupiter engine dependency & fixes

---

extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosImporter.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosImporterTest.java

When video is imported to Koofr and it was not found in CDN, such video should be skipped.
Currently null is returned instead path to video, which breaks creation of successfull ItemImportResult, which requires non-null data.
Short-term solution: return dynamic skipped filepath based on video id.
Potential long term solution: introduce skipped result

Fix skipping not found videos for Koofr

---

extensions/data-transfer/portability-data-transfer-backblaze/src/test/java/org/datatransferproject/datatransfer/backblaze/videos/BackblazeVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-facebook/src/main/java/org/datatransferproject/transfer/facebook/videos/FacebookVideosExporter.java
extensions/data-transfer/portability-data-transfer-facebook/src/test/java/org/datatransferproject/transfer/facebook/videos/FacebookVideosExporterTest.java
extensions/data-transfer/portability-data-transfer-facebook/src/test/java/org/datatransferproject/transfer/facebook/videos/FacebookVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosExporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/common/KoofrMediaExport.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosImporter.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosExporterTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/videos/KoofrVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaExporter.java
portability-spi-transfer/src/test/java/org/datatransferproject/spi/transfer/provider/converter/MediaExporterDecoratorTest.java
portability-spi-transfer/src/test/java/org/datatransferproject/spi/transfer/provider/converter/MediaImporterDecoratorTest.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/videos/VideoModel.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/media/MediaContainerResourceTest.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/videos/VideosContainerResourceTest.java

Adding `uploadedTime` property to the `VideoModel` to bring it inline with the `PhotoModel` in order to make it easier to set the creation time for transferred videos.

issue-963 Add uploadedTime property to VideoModel

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/common/GooglePhotosImportUtils.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporterTest.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/ItemImportResult.java
portability-spi-transfer/src/test/java/org/datatransferproject/spi/transfer/idempotentexecutor/ItemImportResultTest.java

Currently, all videos transferred to Google Photos end up at the top level. They're not assigned to any album. The albums specified via `VideoModel` are ignored.
This change adds support for specifying albums for video transfers. It's duplicating the functionality already present in the `GooglePhotosImporter`. Transfers where the album isn't specified work normally like before.

Add album support to google video importer

---

extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/common/KoofrClient.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/exceptions/KoofrClientIOException.java
extensions/data-transfer/portability-data-transfer-koofr/src/main/java/org/datatransferproject/transfer/koofr/photos/KoofrPhotosImporter.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/common/KoofrClientTest.java
extensions/data-transfer/portability-data-transfer-koofr/src/test/java/org/datatransferproject/transfer/koofr/photos/KoofrPhotosImporterTest.java

Summary:
Upload File endpoint will return 404 when album was deleted in the middle of transfer, such photos should be skipped.
Introducted KoofrClientIOException in order to get code in importer and have centralized error message formatting

Skip photos if album was deleted during transfer

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/drive/DriveImporter.java

This is a straightforward bug in the importer code.
When parent folder id is specified it should be used instead of defaulting to `ROOT_FOLDER_ID`

Fix Google Drive Importer adapter

---

extensions/data-transfer/portability-data-transfer-daybook/src/test/java/org/datatransferproject/transfer/daybook/photos/DaybookPhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-daybook/src/test/java/org/datatransferproject/transfer/daybook/social/DaybookPostsImporterTest.java
portability-api/src/test/java/org/datatransferproject/api/auth/PortabilityAuthServiceExtensionRegistryTest.java

Rules are deprecated in Junit5 hence migrated existing https://github.com/rule to junit 5 equivalents.

Junit4 @Rule migrations to Junit 5

---

portability-types-common/src/main/java/org/datatransferproject/types/common/models/ContainerResource.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/blob/DigitalDocumentWrapper.java
portability-types-common/src/test/java/org/datatransferproject/types/common/models/blob/BlobbyStorageContainerResourceTest.java

Adding `@JsonIgnore` to `getCounts` to make deserialisation work. It's unclear why the document wrapper class inherits `DataModel` in the first place. A better solution would be to remove the inheritance. Scary though
---
This PR is a hotfix so I'll prepare a small release when this diff is merged.

Add de- and serialisation for blobby container resource

---

extensions/data-transfer/portability-data-transfer-daybook/src/main/java/org/datatransferproject/transfer/daybook/social/DaybookPostsImporter.java

Updated Daybook posts importer to log bytes
NOTE: Dependent on https://github.com/google/data-transfer-project/pull/1197
Unlike in the case of other services, we don't seem to upload images in the importer. Instead, image URLs are being included in the form data, so, the size of the same is being logged.

Updated Daybook posts importer to log bytes

---

extensions/copier/portability-stack-copier/src/main/java/org/datatransferproject/copier/stack/PortabilityStackInMemoryDataCopier.java
portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/copier/InMemoryDataCopier.java
portability-transfer/src/main/java/org/datatransferproject/transfer/copier/PortabilityAbstractInMemoryDataCopier.java
portability-transfer/src/main/java/org/datatransferproject/transfer/copier/PortabilityInMemoryDataCopier.java
portability-transfer/src/test/java/org/datatransferproject/transfer/JobProcessorTest.java

This should fix an issue where the errors from the idempotent executor weren't being added to the datastore when the job completed.

Separate getErrors from copy, so it isn't skipped when copy throws.

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosImporter.java

Summary: Capture and throw invalid token exception for video import. This is a temporary check as exception is not properly captured and wrapped into UploadMediaItemResponse error field for videos.
Test Plan: ./gradlew test

Throw invalid token exception for video import

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/common/gphotos/GPhotosUpload.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/media/GoogleMediaImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/media/GoogleMediaImporterTest.java

this is a noop (just refactoring) change to enable a _later_ merge to finally delete duplicate code we took from the GooglePhotosImporter's internals (in the making of GoogleMediaImporter); specifically for the moment, [these lines of code](https://github.com/jzacsh/data-transfer-project/blob/master/extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java#L157-L202) ([permalink](https://github.com/jzacsh/data-transfer-project/blob/2c2336cdbdd63609b88cd40a9a001dde5ab3a05e/extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/photos/GooglePhotosImporter.java#L157-L202)).
we're factoring the code out into a new gphotos package, effectively …

google internal refactoring: factor out batch-import logic so we can (later PR) delete duplication that lives in GooglePhotosImporter

---

extensions/data-transfer/portability-data-transfer-imgur/src/main/java/org/datatransferproject/datatransfer/imgur/photos/ImgurPhotosExporter.java
extensions/data-transfer/portability-data-transfer-imgur/src/test/java/org/datatransferproject/transfer/imgur/photos/ImgurPhotoExporterTest.java

Fix for https://github.com/google/data-transfer-project/issues/1105

Add mocks for InputStream so that Imgur tests do not fail offline

---

extensions/copier/portability-stack-copier/src/main/java/org/datatransferproject/copier/stack/PortabilityStackInMemoryDataCopier.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/idempotentexecutor/InMemoryIdempotentImportExecutorExtension.java
portability-transfer/src/main/java/org/datatransferproject/transfer/Annotations.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerMain.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerModule.java
portability-transfer/src/main/java/org/datatransferproject/transfer/copier/PortabilityAbstractInMemoryDataCopier.java
portability-transfer/src/main/java/org/datatransferproject/transfer/copier/PortabilityInMemoryDataCopier.java
portability-transfer/src/test/java/org/datatransferproject/transfer/copier/PortabilityInMemoryDataCopierTest.java

Change executor to be singleton so that worker and importers/exporters use the same executor. Previously executor used in importers were not getting job id from worker, along with other job info and failed files

Change retrying executor to singleton

---

extensions/auth/portability-auth-google/src/main/java/org/datatransferproject/auth/google/GoogleOAuthConfig.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/GoogleTransferExtension.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/music/GoogleMusicExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/music/GoogleMusicHttpApi.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/music/GoogleMusicImporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/musicModels/BatchPlaylistItemRequest.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/musicModels/CreatePlaylistItemRequest.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/musicModels/GoogleArtist.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/musicModels/GooglePlaylist.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/musicModels/GoogleRelease.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/musicModels/GoogleTrack.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/music/GoogleMusicImporterTest.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/DataVertical.java

- With the latest change in Youtube Music Library Public API, we need to make the same change to google music models.
- We will not the insertion token for playlist anymore. Remove cache mapping in import adapter. 
- Add music to demo server.

Update Google music models and  Import/Export adapters

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/videos/GoogleVideosInterface.java

The Google API can return `org.apache.http.client.HttpResponseException: status code: 401, reason phrase: The upload could not be initialized. Unauthorized` which is essentially a token problem => should be wrapped into `InvalidTokenException`.

throw InvalidTokenException when Google uploadVideo returns HTTP 401

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/mediaModels/GoogleAlbum.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/mediaModels/GoogleAlbumTest.java

Necessary for wrapping our GooglePhotosInterface responses with the RetryingIdempotentExecutor

Made GoogleAlbum serializable; added test to check serializability

---

extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/AppleTransferExtension.java
extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/constants/ApplePhotosConstants.java
extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/constants/AuditKeys.java
extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/photos/AppleMediaImporter.java
extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/photos/AppleMediaInterface.java
extensions/data-transfer/portability-data-transfer-apple/src/test/java/org/datatransferproject/datatransfer/apple/photos/AppleImporterTestBase.java
extensions/data-transfer/portability-data-transfer-apple/src/test/java/org/datatransferproject/datatransfer/apple/photos/AppleMediaImporterTest.java
extensions/data-transfer/portability-data-transfer-apple/src/test/java/org/datatransferproject/datatransfer/apple/photos/ApplePhotosImporterTest.java
extensions/data-transfer/portability-data-transfer-apple/src/test/java/org/datatransferproject/datatransfer/apple/photos/AppleVideosImporterTest.java
extensions/data-transfer/portability-data-transfer-apple/src/test/java/org/datatransferproject/datatransfer/apple/photos/TestConstants.java

The major difficulty I met is that the IdempotentExecutor used by CallableImporter cannot be a retryable executor, so I have to use a different retryable executor in AppleMediaImporter itself.
- Use retryable executor in AppleMediaImporter
- Add Apple Photos error prefix to all errors thrown by AppleMediaInterface
- Please help add the following Apple retry strategy to the yaml config:
- Skippable:  ".\*APPLE PHOTOS IMPORT: Fail to upload content.\*" , ".\*APPLE PHOTOS IMPORT: Fail to create album.\*", ".\*APPLE PHOTOS IMPORT: Fail to create media.\*", ".\*APPLE PHOTOS IMPORT: Fail to get upload url.\*"
- Non-Retryable:  ".\*APPLE PHOTOS IMPORT: iCloud Photos Library not found.\*", ".\*APPLE PHOTOS IMPORT: iCloud Storage is full.\*"

add Retry and skip logic in AppleMediaImporter

---

extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/constants/AppleConstants.java
extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/constants/Headers.java
extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/photos/streaming/StreamingContentClient.java

Add operation group in the content upload request so that Apple can analyze the capacity of DTP Import usage.

add Apple DTP import operation group

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/mediaModels/GoogleMediaItem.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/mediaModels/GoogleMediaItemTest.java

this is fixing a single time-mishandling issue that uncovered two orthogonal problems:
- 1. "correct time" issue: json parsing dropped timezone/offset specifiers as we were using a hand-crafted formatter string. Switching us to a standard library one that accepts both `Z` alias (for greenwhich) and offsets (like `+00:00`). Gphotos api docs[a] (inlined into the code) shows we use the former, which is what the unit test uses as well.
- this probably meant time metadata for content transferred was off by some number of due to timezone being dropped
- 2. "brittle unit test": unit test was relying on machine-specific `gradle test` behavior, so an out of the box `git checkout master` had two failing tests for me[b] but not for our github ci/cd.
- this was due to use of `toString()` (in our …

bugfix: use correct time; fix brittle unit test

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/mediaModels/GoogleMediaItem.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/mediaModels/GoogleMediaItemTest.java

nitfix: encode high-precision stamp from docs
once encoding a high-precision stamp in the docs we see the unit test
fails because we're using a differet parsers than the unit test itself.
Document what we're using and make it visible for testing.

nitfix: encode high-precision stamp from docs

---

extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/photos/AppleMediaInterface.java

ImmutableMap is being used to log error cases during a transfer. Unfortunately said error cases are _themselves_ obfuscated by a less interesting `NullPointerException` due to ImmutableMap receiving nulls.
ImmutableMap doesn't allow null values (see guava's issues 1782) but it's being passed an `albumId` sometimes set to null. This might be happening in multiple places but I've at least seen it in the primary download/upload loop (on line 588, before this change).

bugfix: NullPointerExc swallowing real errors

---

portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryMapping.java
portability-types-transfer/src/main/java/org/datatransferproject/types/transfer/retry/RetryStrategyLibrary.java

this is a new feature that should have no impact on existing RetryStrategy yaml/json users: there's simply a new `stacktraceRegexes` key in the config that acts as an alternative to the older `regexes`. It's only difference from the original is that its regexes match across the long, multi-line strings that are **full** stacktraces.
motivation: matching more of the Throwable is a TODO that's come up multiple times and now actually caused a surprise last-minute bug for us, so this patch resolves the feature gap and unblocks google's and apple's work.
testing: for now we're leaving backfilling (a new unit test for this file) as a fast-follow, since Google has intern integration~esque unit-test coverage of this file against our real-world YAML config. Not ideal, but need time to come back …

resolve TODO: match full stacktrace retry strategy

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/music/GoogleMusicHttpApi.java

Apple Music -> YouTube Music flow has long latency when importing playlists. Each importing iteration takes around 100-125sec. YouTube Music Importing APIs' latency is around 5s. Reducing blocking read time out should help reduce the time per playlist.

Decrease Google Music Post Request read timeout

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/music/GoogleMusicHttpApi.java

Increase the read timeout to 30 seconds since the latency of ImportPlaylist API may go up to 12 seconds.

Fine tune music importer post request read timeout

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/music/GoogleMusicImporter.java

YouTube music has 5000 tracks per playlist limitation. We want to make it as skippable failure for initial launch.

Make track limitation in YouTube Music as skippable failure

---

extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/constants/AppleMusicConstants.java
extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/music/AppleMusicImporter.java
extensions/data-transfer/portability-data-transfer-apple/src/test/java/org/datatransferproject/datatransfer/apple/music/AppleMusicImporterTest.java
portability-types-common/src/main/java/org/datatransferproject/types/common/models/music/MusicContainerResource.java

We were trying to figure out why no counts were written for MUSIC jobs even though the AppleMusicImporter sets the counts here: https://github.com/dtinit/data-transfer-project/blob/822e0e7f0750f2cbf6de8cb2948601842d3b62e3/extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/music/AppleMusicImporter.java#L91-L97 
And this should be preserved the same way photos counts are preserved
Upon investigating it looks like we completely disregard the counts returned from the importer in favor of the counts that are with the original exported data here: https://github.com/dtinit/data-transfer-project/blob/822e0e7f0750f2cbf6de8cb2948601842d3b62e3/portability-transfer/src/main/java/org/datatransferproject/transfer/CallableImporter.java#L80 …

Add counts to MusicMediaContainer

---

portability-transfer/src/main/java/org/datatransferproject/transfer/JobProcessor.java
portability-transfer/src/main/java/org/datatransferproject/transfer/WorkerModule.java

We're seeing a guice error when trying to start a worker, this looks like its happening because the JobProcessor is looking for an `@Named` object while the WorkerModule provides it as an `@Flag` object (and also isnt marked as `@Provides`). Im not sure what the original usecase of the `@Flag` argument is for but it also doesnt look like we use it outside of the extension contexts 
```
2024-09-11 14:30:28.888676-05001   [34mINFO 2024-09-11T19:30:28.889469 Using InMemoryDataCopier: org.datatransferproject.transfer.copier.PortabilityInMemoryDataCopier[0m
2024-09-11 14:30:29.045224-05001   Sep 11, 2024 7:30:29 PM com.google.common.util.concurrent.UncaughtExceptionHandlers$Exiter uncaughtException
2024-09-11 14:30:29.045244-05001   SEVERE: Caught an exception in Thread[#1,main,5,main]. …
```

Fix Guice Injection error with transferSignalEnabled flag

---

portability-transfer/src/main/java/org/datatransferproject/transfer/JobPollingService.java

This check was originally added in 9d5302c, where it was used to check that two workers didn't attempt to claim the same job. Since then the surrounding code has seen a lot of refactoring, including migrating to calling `claimJob` on the job store which, per the comment in `JobPollingService` and on the `JobStore` interface docs, should do the job of ensuring this doesn't happen.
Removing this line unblocks the option of allowing workers to reclaim jobs from another crashed worker that couldn't inform the job store it was exiting (e.g. OOM killed), but also continues to allow blocking `claimJob` on claimed jobs by delegating that decision to the `JobStore`.

Remove check for `authPublicKey` when claiming jobs

---

portability-types-transfer/README.md

Removes broken internal documentation link, adds new one, and adds more language suggested by jzacsh
Fixes #1056

Internal documentation fixes (issue 1056)

---

CONTRIBUTING.md
Documentation/Developer.md

* Adds a bit more info about what a contributor is likely to need to know on behalf of their org, to successfully make a contribution
* Remove unused communication mechanisms
* Fix link to old site with white papers
* Adds lightweight policy for what we do with a PR when the CLA isn't signed
* Remove reference to "good first issue" tagged issues as we removed those tags - they were generally still very hard for new contributors to actually fix.

Updates some of the information for contributors

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaImporterTest.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/photos/MicrosoftPhotosImporterTest.java

I have to fight this everytime I'm working on or fixing something in this adapter (so that my PRs are easier to read and aren't mixed in with this enormous diff). So just letting it finally run once and for all, and merge it as a standalone PR so it's clearly separated from any other changes one might be trying to debug.
for more, see the extant DTP documentation on developer setup: https://github.com/dtinit/data-transfer-project/blob/badda9bb520e59cd13227e2f4a9e4189b0bc7e59/Documentation/Developer.md#setup-formatting (I'm not using intellij, but google-java-format exists in every editor I've used, so the instructions should still stand).

noop(cleanup) run clang-format (enforce goog style)

---

.github/workflows/codeql-analysis.yml
.github/workflows/gradle.yml

```sh
$ find .github/ -type f -exec \
sed -Ei 's,actions?\/(.*)\@v[[:digit:]],actions/\1\@v3,g' {} \;
```
unsure if any action names changed (so unsure this will work), but guessing ci/cd will tell us.
part part of #1397

fix: EOL'd github actions: upgrade all that are possible to upgrade

---

.gitignore

example of this really coming up: https://github.com/dtinit/data-transfer-project/pull/1401#pullrequestreview-2482420787
and then it's continued to happen all day for me.

workaround annoying .attach_pid1234 files

---

build.gradle

for example, a download/tar of a repo often doesn't have a vcs. it's quite common to just fall back to "unknown", so I'm doing that.
without this commit, you cannot build or test this project:
```sh
$ ./gradlew --watch-fs --continuous --console=rich -Dorg.gradle.java.home=/usr/lib/jvm/java-11-openjdk-amd64 test
<-------------> 0% CONFIGURING [17ms]
> Loading projects
FAILURE: Build failed with an exception.
* Where:
Build file 'build.gradle' line: 218
* What went wrong:
A problem occurred evaluating root project 'org.datatransferproject'.
> Cannot invoke method getObjectId() on null object
* Try:
Run with --stacktra
> Configure project :
Node installation: local, Cloud type: local
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use …
```

gradle need not depend on ./git/ (vcs)

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/MicrosoftApiResponse.java
extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/MicrosoftApiResponseTest.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaImporterTest.java

while we're at it, just take what we need (unmarshal into a string) and close it ourselves, letting caller stop worrrying about this closeable.
while we're he we *also* cleanup all our unit tests so they use real Response objects, and stop mocking it. (This is the same recent codehealth change made to stop using ResponseBody mocks, and use the real things). Not interacting with the real OkHTTP API was part of what made this issue invisible before.

fix: illegalstatexception: reading responses that are always closed

---

extensions/data-transfer/portability-data-transfer-apple/src/test/java/org/datatransferproject/datatransfer/apple/music/AppleMusicImporterTest.java

the arrangement logic accidentally guaranteed a 1/100 chance we would get a failure (range was `[0,100)` but we want `[1,...)` instead)
fixed #1411

bugfix: fix flakiness in apple music adapter test: ensure non-zero test-content

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/MicrosoftApiResponse.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/MicrosoftApiResponseTest.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaImporterTest.java

regression coverage: without the fix in MicrosoftApiResponse.java this new test's state captures `isTokenRefreshRequired()` erroneously returning true:
```
MicrosoftApiResponseTest > testDestinationFull PASSED
MicrosoftApiResponseTest > testUnrecognized401 FAILED
java.lang.AssertionError: The subject was expected to be false, but was true
at org.datatransferproject.transfer.microsoft.MicrosoftApiResponseTest.testUnrecognized401(MicrosoftApiResponseTest.java:130)
MicrosoftApiResponseTest > testBytesOnClosedResponse PASSED
MicrosoftApiResponseTest > testOkay PASSED
MicrosoftApiResponseTest > testInvalidTokenDetection PASSED
MicrosoftApiResponseTest > testErrorPermission PASSED
MicrosoftApiResponseTest > testErrorUnknown PASSED
MicrosoftMediaImporterTest > testImportItemAllSuccess PASSED …
```

fix(microsoft): 401s only sometimes correctly classified

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaImporter.java
extensions/data-transfer/portability-data-transfer-microsoft/src/test/java/org/datatransferproject/transfer/microsoft/media/MicrosoftMediaImporterTest.java

we're sometimes seeing the following microsoft server response at the `uploadChunk()` callsite:
```
MicrosoftApiResponse{httpStatus=401, httpMessage=, body=Optional[
{
"error": {
"code": "unauthenticated",
"message": "Unauthenticated"
}
}
]}
```
which according to their documentation is because we simply aren't supposed to send the token during our chunked byte-upload sequence (PUT), but only during our createSession (POST) call at the start:
> If you include the Authorization header when issuing the `PUT` call,
> it may result in an `HTTP 401 Unauthorized` response. Only send the
> Authorization header and bearer token when issuing the `POST` during
> the first step. Don't include it when you issue the `PUT` call.
-- https://learn.microsoft.com/en-us/graph/api/driveitem-createuploadsessio …

fixes microsoft server _sometimes_ failing due to un-required token

---

.github/workflows/commitlint.yml
CONTRIBUTING.md

In preparation for automating the release process, adds a check to start linting PR titles based on [conventional commits](https://conventionalcommits.org).

ci: add conventional commit lint check to PR titles

---

.github/dependabot.yml

Makes dependabot use conventional-commit style PR titles

ci(dependabot): use conventional commit messages

---

portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/ConsoleMonitor.java

right now there was no way to opt-out of color (ANSI escape sequences for terminal emulators to capture/interpret). Give us a mechanism to control this now and also make it opt _in_ (so if someone's doing a local demo and wants fancy colors they now just have to do  `export FORCE_COLOR=1` or `FORCE_COLOR=1 ./gradlew ...`).
Even if this is for someone's local machine, it's a debugging task, and that involves head-scratching many minutes/hours/days later, and communicating with other people _themselves_ in different timezones. So including a timezone only helps us here.
this isn't an interactive CLI where stdout and sterr are distinguished, but rather a long-running server's own log output. As such, stop using stdout since there's no "nice" output: all output is for debugging purposes (and …

fix: TTY logs more robust for debugging, use stderr, don't default to w/escape codes

---

extensions/data-transfer/portability-data-transfer-generic/README.md
extensions/data-transfer/portability-data-transfer-generic/src/main/java/org/datatransferproject/datatransfer/generic/GenericFileImporter.java
extensions/data-transfer/portability-data-transfer-generic/src/main/java/org/datatransferproject/datatransfer/generic/GenericImporter.java
extensions/data-transfer/portability-data-transfer-generic/src/main/java/org/datatransferproject/datatransfer/generic/auth/OAuthTokenManager.java
extensions/data-transfer/portability-data-transfer-generic/src/test/java/org/datatransferproject/datatransfer/generic/GenericImporterTest.java

Fixes #1424.
Generic importers will throw `DestinationMemoryFullException`(which extends `CopyExceptionWithFailureReason`) when any of the import post API implemented by client throws error with code: `413` & error: `destination_full`

feat: Destination Full support for Generic Importers 

---

.cz.toml
.github/workflows/commitlint.yml
.github/workflows/release.yml
CONTRIBUTING.md
Documentation/Publishing.md
build.gradle
gradle.properties

Creates a new github action pipeline that runs on merge to `master`. The pipeline will:
1. Create a new commit with an updated CHANGELOG.md
2. Tag that commit and push it to `master`
3. Make a clean checkout of that commit
4. Build, sign, and release all java artefacts to maven
Depends on #1422 to set up the secrets in github

ci: release to maven on merge

---

.cz.toml
.github/workflows/release.yml
Documentation/Publishing.md
build.gradle
gradle.properties
portability-transfer/build.gradle

Committing to the master branch isn't allowed from github actions because of our branch protection rules. There's no easy way to allow github actions to bypass this.
As a workaround, skip all the parts of the release that needed to commit to the repo. This means moving the version config to an environment variable, which shouldn't be an issue, and using git tags as the source of truth.

ci: release without committing to main branch

---

build.gradle

This is required to sign the pom when uploading artifacts
Ran an test upload to validate it end-to-end:

fix(ci): set up signing at root project level

---

extensions/data-transfer/portability-data-transfer-generic/src/main/java/org/datatransferproject/datatransfer/generic/ContainerSerializer.java
extensions/data-transfer/portability-data-transfer-generic/src/main/java/org/datatransferproject/datatransfer/generic/GenericImporter.java

The `ContainerSerializer` interface needs to be public for any package other than `org.datatranfserproject.datatransfer.generic` to be able to instantiate a `GenericImporter`.
We want to implement a custom `GenericTransferExtension` that can load from a database rather than packaged config file, so need to be able to instantiate `GenericImporter`s from a different package.

fix(generic): make ContainerSerializer interface public

---

portability-api-launcher/src/main/java/org/datatransferproject/launcher/monitor/ConsoleMonitor.java

fix: prevent crashes due to off-chance strings will _actually_ have `%` chars inside, looking like a format string.
background-context: the last change (#1425) to this line was intended to switch from `out` to `err`, not to change the method of choice (that was just an accident of habitual-typing).
This was able to sometimes cause a crash on an invocation to log because `java.util.Formatter.parse` would see a formatter symbol (`%`) then try to make sense of it or match it to another arg (of which we pass no other args). All a mistake anyway: we didn't want `format()` to begin with.

fix: prevent crashes due to off-chance strings are really format-looking

---

extensions/data-transfer/portability-data-transfer-generic/src/main/java/org/datatransferproject/datatransfer/generic/auth/OAuthTokenManager.java
extensions/data-transfer/portability-data-transfer-generic/src/test/java/org/datatransferproject/datatransfer/generic/auth/OAuthTokenManagerTest.java

don't fail on unknown properties while deserialising RefreshTokenResponse

fix(generic): don't fail on unknown properties while deserialising RefreshTokenResponse

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/provider/TransferCompatibilityProvider.java
portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/provider/converter/AnyToAnyImporter.java

this is entirely a change for code clarity, because if you read (before this patch) the `AnyToAnyImporter#import` generic-params you'll see `To` being passed in as the source of data (what should be a conceptual "From").
The cause of that confusion is that there's multiple different orthogonal transformations happening with/around the `TransferCompatibilityProvider` and its supporting `AnyToAnyImporter` class and DTP generally:
1. DTP moves data from a Exporter producing models to an Importer consuming models
1. we have static functions that convert model A to model B (eg: from Photos model to a Media model via [`MediaContainerResource::photoToMedia`][pToMedia])
- this is parallel to the `From` and `To` generic params of [`java.util.function.Function<From, To>`][Function].
1. …

refactor: codehealth rename types to reflect axis of transformation

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/types/TempMediaData.java

refactor: TempMediaData techdebt-progress:  this cleansup/unblocks upcoming 'static exporter' I've written that will utilize this exact same code, but won't be tied to any one DTP model.

refactor: (noop; new API) further carve out model-agnostic interface for

---

portability-spi-transfer/src/main/java/org/datatransferproject/spi/transfer/provider/Exporter.java

the `Importer` interface probably needs similar love, but figure this is a net-win for the moment.

docs: (noop) better explain `Exporter` interface's contract

---

extensions/data-transfer/portability-data-transfer-microsoft/src/main/java/org/datatransferproject/transfer/microsoft/MicrosoftApiResponse.java

nit: bodyException() is being populated but never read, which someone… will *really* not appreciate when they try to make sense of a stacktrace some day

refactor: include more info in Microsoft stacktrace, when/if available

---

extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/constants/Headers.java
extensions/data-transfer/portability-data-transfer-apple/src/main/java/org/datatransferproject/datatransfer/apple/signals/AppleSignalInterface.java

Setting Content-Type and Accept Headers to "application/json" for `AppleSignalInterface`.

fix: Add Content-Type and Accept Headers

---

extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/music/GoogleMusicExporter.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/music/GoogleMusicHttpApi.java
extensions/data-transfer/portability-data-transfer-google/src/main/java/org/datatransferproject/datatransfer/google/musicModels/ExportReleaseResponse.java
extensions/data-transfer/portability-data-transfer-google/src/test/java/org/datatransferproject/datatransfer/google/music/GoogleMusicExporterTest.java

Enables the support for exporting music releases from Google.

feat: google music release exporter
